//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.contracts = new HashSet<contract>();
        }
    
        public int company_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string employee_name { get; set; }
        public string employee_phone { get; set; }
        public string email { get; set; }
        public Nullable<int> type { get; set; }
        public int interactive_counter { get; set; }
        public string tax_code { get; set; }
        public string bank_name { get; set; }
        public string bank_account { get; set; }
        public string bank_branch { get; set; }
        public string bank_number { get; set; }
        public Nullable<int> call_date { get; set; }
        public Nullable<int> call_again_date { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string code { get; set; }
        public int status { get; set; }
    
        public virtual admin admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
    }
}
