//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_employee
    {
        public int contract_employee_id { get; set; }
        public int contract_id { get; set; }
        public int employee_id { get; set; }
        public string work_date { get; set; }
        public Nullable<int> work_hour { get; set; }
        public int from_date { get; set; }
        public Nullable<int> to_date { get; set; }
        public int status { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual employee employee { get; set; }
    }
}
