//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract_note
    {
        public int contract_note_id { get; set; }
        public int contract_id { get; set; }
        public string note { get; set; }
        public int created_date { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual employee employee { get; set; }
    }
}
