//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class problem_image
    {
        public int problem_image_id { get; set; }
        public int problem_id { get; set; }
        public string img { get; set; }
    
        public virtual problem problem { get; set; }
    }
}
