//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_visit_history
    {
        public int user_visit_history_id { get; set; }
        public int user_visit_item_id { get; set; }
        public int expected_date { get; set; }
        public int actual_date { get; set; }
    
        public virtual user_visit_item user_visit_item { get; set; }
    }
}
