//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        public int user_account_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int user_profile_id { get; set; }
        public string avatar { get; set; }
    
        public virtual user_profile user_profile { get; set; }
    }
}
