//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_social
    {
        public int user_social_id { get; set; }
        public string email { get; set; }
        public int user_profile_id { get; set; }
        public int type { get; set; }
    
        public virtual user_profile user_profile { get; set; }
    }
}
