var translationsVI = {
    menu_customer: "Hỗ trợ",
    menu_signup: "Đăng ký",

    btn_register: "Đăng ký",
    blog_news:"Tin Tức",
    blog_experience:"Kinh Nghiệm",
    blog_keyword:"Từ khóa",
    blog_search:"Tìm kiếm",
    blog_readmore:"Xem thêm",
    host_save:"Lưu",
    host_chooseyourapartment:"Chọn căn hộ của bạn",
    host_tenant:"Người thuê nhà",
    host_overview:"Tổng quan",
    host_problem:"Vấn đề",
    host_describe:"Miêu tả",
    host_information:"Thông tin",
    host_photos:"Ảnh",
    host_location:"Vị trí",
    host_time:"Thời gian",
    host_billingdetail:"Chi tiết thanh toán",
    host_property:"Bất động sản",
    host_article:"Vật phẩm",
    host_datebilled:"Ngày lập hóa đơn",
    host_amountbilled:"Chi phí",
    host_paymentstatus:"Thanh toán",
    host_detailcase:"Chi tiết các trường hợp",
    host_calendar:"Lịch",
    host_downloadcontract:"Tải hợp đồng",
    host_name:"Tên",
    host_type:"Loại",
    host_project:"Dự án",
    host_nobedroom:"Số phòng ngủ",
    host_nobathroom:"Số phòng tắm",
    host_area:"Diện tích",
    host_address:"Địa chỉ",
    host_enteralocation:"Nhập địa chỉ",
    host_addbannerimage:"Thêm ảnh",
    host_addanother:"Thêm ảnh",
    host_dragthepintoadjustitslocation:"",
    project_featureproject:"CÁC ĐẶC TRƯNG CỦA DỰ ÁN",
    project_onairproject:"Dự án đang triển khai",
    project_explore:"Khám phá",
    project_seelist:"Xem danh sách",
    project_upcomingproject:"Dự án sắp triển khai",



}

var translationsEN = {
    search_bar_livingHaNoi: "Easy living in HaNoi",
    search_bar_price: "Price",
    search_bar_room: "Room",
    search_bar_area: "Area",
    search_bar_facilities: "Facilities",
    menu_support:"Support",
    menu_blog: "Blog",
    menu_customer: "Support",
    menu_signup: "Sign up",
    menu_help: "Help",
    menu_login: "Login",
    menu_visit: "Your visit list",
    menu_host: "Become a host",
    btn_register: "Signup",
    blog_news:"News",
    blog_experience:"Experience",
    blog_keyword:"Keyword",
    blog_search:"Search",
    blog_readmore:"Read More",
    host_save:"Save",
    host_chooseyourapartment:"Choose your apartment",
    host_tenant:"tenant",
    host_overview:"Overview",
    host_problem:"Problem",
    host_describe:"Describe",
    host_information:"Information",
    host_photos:"Photos",
    host_location:"Location",
    host_time:"Time",
    host_billingdetail:"Billing Detail",
    host_property:"Property",
    host_article:"Article",
    host_datebilled:"Date Billed",
    host_amountbilled:"Amount Billed",
    host_paymentstatus:"Payment Status",
    host_detailcase:"Detail Case",
    host_calendar:"Calendar",
    host_downloadcontract:"Download Contract",
    host_name:"Name",
    host_type:"Type",
    host_project:"Project",
    host_nobedroom:"No.Bedroom",
    host_nobathroom:"No.Bathroom",
    host_area:"Area",
    host_address:"Address",
    host_enteralocation:"Enter a location",
    host_addbannerimage:"Add banner image",
    host_addanother:"Add another",
    host_dragthepintoadjustitslocation:"Drag the pin to adjust its location",
    project_featureproject:"FEATURE PROJECT",
    project_onairproject:"ON-AIR PROJECT",
    project_explore:"Explore",
    project_seelist:"See list",
    project_upcomingproject:"UP-COMING PROJECT",

}

var translationsJP = {
    menu_customer: "サポート",
    menu_signup: "サインアップ",

    btn_register: "サインアップ",
    blog_news:"ニュース",
    blog_experience:"経験",
    blog_keyword:"キーワード",
    blog_search:"サーチ",
    blog_readmore:"続きを読む",
    host_save:"保存する",
    host_chooseyourapartment:"あなたのアパートを選択する",
    host_tenant:"テナント",
    host_overview:"概要",
    host_problem:"問題",
    host_describe:"説明する",
    host_information:"情報",
    host_photos:"写真",
    host_location:"ロケーション",
    host_time:"時間",
    host_billingdetail:"請求の詳細",
    host_property:"プロパティ",
    host_article:"記事",
    host_datebilled:"請求書日付",
    host_amountbilled:"請求額",
    host_paymentstatus:"支払い状況",
    host_detailcase:"詳細ケース",
    host_calendar:"カレンダー",
    host_downloadcontract:"契約をダウンロードする",
    host_name:"名",
    host_type:"タイプ",
    host_project:"プロジェクト",
    host_nobedroom:"ベッドルームの数",
    host_nobathroom:"バスルームの数",
    host_area:"エリア",
    host_address:"住所",
    host_enteralocation:"場所を入力してください",
    host_addbannerimage:"バナー画像を追加する",
    host_addanother:"別のものを追加する",
    host_dragthepintoadjustitslocation:"ピンをドラッグして位置を調整する",
    project_featureproject:"フィーチャープロジェクト",
    project_onairproject:"オンエアプロジェクト",
    project_explore:"探検する",
    project_seelist:"リストを見る",
    project_upcomingproject:"アップ・アップ・プロジェクト",

}

app.config(['$translateProvider', function ($translateProvider) {
    // add translation tables
    $translateProvider.translations('en', translationsEN);
    $translateProvider.translations('vi', translationsVI);
    $translateProvider.translations('jp', translationsJP);
    $translateProvider.preferredLanguage('en');
    $translateProvider.fallbackLanguage('vi');
    $translateProvider.fallbackLanguage('jp');
}]);