var translationsVI = {
    menu_customer: "Hỗ trợ",
    menu_signup: "Đăng ký",
    menu_support:"Hỗ trợ",
    menu_blog: "Blog",
    menu_about_us: "Về chúng tôi",
    menu_help: "Trợ giúp",
    menu_login: "Đăng nhập",
    menu_visit: "Danh sách nhà thăm",
    menu_host: "Chủ nhà",
    btn_register: "Đăng ký",
    blog_news:"Tin Tức",
    blog_experience:"Kinh Nghiệm",
    blog_tips:"Lời Khuyên",
    blog_keyword:"Từ khóa",
    blog_search:"Tìm kiếm",
    blog_readmore:"ĐỌC TIẾP",
    blog_loadmore:"Xem thêm",
    host_save:"Lưu",
    host_chooseyourapartment:"Chọn căn hộ của bạn",
    host_tenant:"Người thuê nhà",
    host_overview:"Tổng quan",
    host_problem:"Vấn đề",
    host_describe:"Miêu tả",
    host_information:"Thông tin",
    host_photos:"Ảnh",
    host_location:"Vị trí",
    host_time:"Thời gian",
    host_billingdetail:"Chi tiết thanh toán",
    host_property:"Bất động sản",
    host_article:"Vật phẩm",
    host_datebilled:"Ngày lập hóa đơn",
    host_amountbilled:"Chi phí",
    host_paymentstatus:"Thanh toán",
    host_detailcase:"Chi tiết các trường hợp",
    host_calendar:"Lịch",
    host_downloadcontract:"Tải hợp đồng",
    host_name:"Tên",
    host_type:"Loại",
    host_project:"Dự án",
    host_nobedroom:"Số phòng ngủ",
    host_nobathroom:"Số phòng tắm",
    host_area:"Diện tích",
    host_address:"Địa chỉ",
    host_enteralocation:"Nhập địa chỉ",
    host_addbannerimage:"Thêm ảnh",
    host_addanother:"Thêm ảnh",
    host_thumbnail:"Ảnh thu nhỏ",
    host_banner:"-ảnh biểu ngữ",
    host_dragthepintoadjustitslocation:"Kéo ghim để điều chỉnh vị trí của nó",
    project_featureproject:"CÁC ĐẶC TRƯNG CỦA DỰ ÁN",
    project_onairproject:"DỰ ÁN ĐANG TRIỂN KHAI",
    project_explore:"Khám phá",
    project_seelist:"Xem danh sách",
    project_upcomingproject:"DỰ ÁN SẮP TRIỂN KHAI",


    price_range:"Phạm vi giá",
    clear:"Làm mới",
    rooms:"Các phòng",
    bedrooms:"Phòng ngủ",
    bathrooms:"Phòng tắm",
    area:"Diện tích",
    facilities:"Cơ sở vật chất",
    introducing_property_plus:"Giới thiệu Property Plus",
    explore_our_story:"Về chúng tôi",
    see_how_our_service_is_best:"Các dịch vụ tốt nhất của chúng tôi",
    standard_quality:"Tiêu chuẩn chất lượng",
    fast_service:"Dịch vụ nhanh",
    call_center:"Trung tâm cuộc gọi 24/7",
    multi_language_support:"Hỗ trợ đa ngôn ngữ",
    explore_all_service:"Về các dịch vụ",
    choose_your_new_home:"Chọn nhà mới của bạn",
    estimate_price:"Giá ước tính",
    see_more:"Xem thêm",
    project_have_our_service:"Dự án có dịch vụ của chúng tôi",
    explore_all:"Xem tất cả",
    show_map:"Hiện bản đồ",
    view_category:"KIỂU XEM",
    apartment_uppercase:"Căn hộ",
    night_text:"đêm",
    share_text:"Chia sẻ",
    bookmark_text:"Đã lưu",
    about_this_listing:"VỀ DANH SÁCH NÀY",
    tour_this_home:"THĂM QUAN NHÀ",
    living_room:"Phòng khách",
    other_text:"Khác",
    amenities:"TIỆN NGHI",
    owner:"Chủ sở hữu",
    join_in:"Tham gia từ",
    estimate_price_included_service:"Giá ước tính bao gồm dịch vụ",
    per_text:"mỗi",
    apartment_price:"Giá căn hộ",
    month_text:"tháng",
    service_total_price:"Tổng giá dịch vụ",
    service_package:"Gói dịch vụ",
    custom:"Tùy chọn",
    basic:"Cơ bản",
    management_fee_by:"Phí quản lý bởi PP",
    foreign_tv:"TV Nước ngoài",
    laundry_cleaning:"Giặt là",
    drinking_water:"Nước uống",
    detergent:"Chất tẩy rửa",
    toilet_paper:"giấy vệ sinh",
    electric_water_bill:"Hóa đơn điện và nước",
    include_tax:"Bao gồm thuế",
    send_visiting_request:"GỬI YÊU CẦU LỊCH HẸN",
    similiar_listing:"DANH SÁCH TƯƠNG TỰ",
    bookmark_uppercase:"ĐÃ LƯU",
    dashboard:"Quản trị",
    manage:"Quản lý",
    listing:"Danh sách",
    help:"Hỗ trợ",
    edit_profile:"Chỉnh sửa hồ sơ",
    account_setting:"Cài đặt tài khoản",
    logout:"Thoát",
    provide_information:"Cung cấp thông tin",
    upload_picture:"Tải ảnh",
    set_price:"Đặt giá",
    verify:"Kiểm chứng",
    congratulation_finish:"Xin chúc mừng, việc tải lên căn hộ của bạn đã kết thúc. Nó sẽ sớm xuất hiện.",
    home:"Trang chủ",
    create_new:"Tạo mới",
    row_1_step_1_1:"Hãy bắt đầu liệt kê căn hộ của bạn",
    row_2_step_1_1:"Bạn có loại bất động sản nào?",    
    row_3_step_1_1:"Tên dự án của bạn",
    continue:"Tiếp tục",
    row_1_step_1_2:"Hãy cho chúng tôi biết thêm về căn hộ của bạn",
    row_2_step_1_2:"Tổng số phòng ngủ của căn hộ sở hữu ?",
    row_3_step_1_2:"Tổng số phòng tắm của căn hộ sở hữu ?",
    row_4_step_1_2:"Diện tích của căn hộ",
    area_required:"Diện tích không được bỏ trống",
    address_required:"Địa chỉ chưa đúng định dạng",
    phone:"Số điện thoại",
    phone_required:"Số điện thoại chưa đúng định dạng",
    row_5_step_1_2:"Tên căn hộ ( Không bắt buộc )",
    row_6_step_1_2:"Mô tả về căn hộ ( Không bắt buộc )",
    next:"Tiếp theo",
    cancel:"Hủy",
    back:"Quay lại",
    row_1_step_1_3:"Đây có đúng là vị trí căn hộ của bạn?",
    row_2_step_1_3:"Nếu cần, bạn có thể kéo ghim để điều chỉnh vị trí của nó.",
    add_banner_image:"Thêm ảnh bìa",
    great_progress:"Tiến độ tuyệt vời!",
    row_1_step_2_1:"Bây giờ chúng ta hãy lấy một số chi tiết về căn hộ của bạn sau đó bạn có thể sẵn sàng để xuất bản danh sách của bạn.",
    row_2_step_2_1:"Lời khuyên: Căn hộ có hình ảnh thực tế giúp cho thuê quyết định nhanh hơn.",   
    add_another:"Tải ảnh khác", 
    row_1_step_3_1:"Thiết lập giá cho căn hộ của bạn",
    row_2_step_3_1:"Phí quản lý căn hộ",
    row_3_step_3_1:"Căn hộ tương tự",
    row_1_step_3_2:"Chọn cơ sở vật chất của căn hộ",
    row_1_step_4_1:"Để có cơ sở pháp lý để kinh doanh trên PROPERTYPLUS, vui lòng đăng ảnh hoặc bản sao chụp giấy chứng nhận quyền sở hữu đất hoặc thư ủy quyền sử dụng tài sản.",
    row_2_step_4_1:"- Không upload ảnh dung lượng quá 5mb.",
    row_3_step_4_1:"- Số lượng ảnh upload không vượt quá 5.",
    row_4_step_4_1:"Kéo hoặc thả để tải ảnh lên ",
    finish:"Hoàn thành",
    all:"Tất cả",
    listed:"Liệt kê",
    description:"Mô tả",
    listing_on_project:"DANH SÁCH DỰ ÁN",
    general:"Cài đặt chung",
    host_text:"Chủ nhà",
    public_infomation:"Thông tin công khai",
    full_name:"Tên đầy đủ",
    profile_photo:"Ảnh đại diện",
    row_1_edit_profile:"Hình ảnh mặt trước rõ ràng là một cách quan trọng để chủ và khách tìm hiểu về nhau. Hãy chắc chắn sử dụng ảnh hiển thị rõ ràng khuôn mặt của bạn và không bao gồm bất kỳ thông tin cá nhân hoặc nhạy cảm nào mà bạn không muốn chủ nhà hoặc người thuê xem thấy.",
    upload_ava_text:"Tải lên một ảnh",
    private_infomation:"Thông tin riêng tư",
    row_2_edit_profile:"Chúng tôi sẽ không bao giờ chia sẻ thông tin cá nhân của bạn với người dùng Property Plus khác.",
    i_am:"Tôi là",
    birth_date:"Ngày sinh",
    email:"Email",
    phone_number:"Số điện thoại",
    verification:"Xác minh",
    row_3_edit_profile:"Bạn sẽ cần cung cấp thông tin nhận dạng khi bạn thực hiện hợp đồng thuê, vì vậy hãy bắt đầu bằng cách thực hiện ngay bây giờ.",
    upload:"Tải lên",
    option_infomation:"Thông tin tùy chọn",
    company:"Công ty",
    company_address:"Địa chỉ công ty",
    row_4_edit_profile:"Cung cấp cho nhóm Dịch vụ khách hàng của chúng tôi một liên hệ đáng tin cậy mà chúng tôi có thể cảnh báo trong tình huống khẩn cấp.",
    describe_yourself:"Mô tả về bản thân",
    your_visiting_list:"Danh sách lịch hẹn của bạn",
    your_apartment:"Căn hộ của bạn",
    visting_schedule:"Lịch hẹn",
    visting_history:"Lịch sử hẹn",
    you_visited:"Bạn đã thăm",
    apartment:"căn hộ",
    billing:"Thanh toán",
    send_issue:"Gửi sự cố",
    your_using_service:"Bạn đang sử dụng dịch vụ",
    service:"Dịch vụ",
    quantity:"Số lượng",
    maintance_management:"Quản lý và bảo trì",
    default:"mặc định",
    cable_tv:"Cáp TV",
    times:"lần",
    week:"tuần",
    bottles:"bình",
    change:"Thay đổi",
    current_balance:"Số dư hiện tại",
    electricity_charge:"Tiền điện",
    not_paid:"Chưa thanh toán",
    paid:"Đã thanh toán",
    hot_water_charge:"Phí nước nóng",
    cold_water_charge:"Phí nước lạnh",
    report_a_problem:"Báo cáo sự cố",
    support_inbox:"Hòm thư hỗ trợ",
    reported_billing_issue:"Bạn đã báo cáo sự cố thanh toán",
    last_update:"Cập nhật cuối cùng",
    sending:"ĐANG GỬI",
    solved:"ĐÃ GIẢI QUYẾT",
    in_progress:"TRONG TIẾN TRÌNH",
    we_sent_you_a_message:"Chúng tôi gửi cho bạn 1 tin nhắn",
    rate_your_experience:"Đánh giá của bạn",
    change_your_password:"Thay đổi mật khẩu",
    old_password:"Mật khẩu cũ",
    new_password:"Mật khẩu mới",
    confirm_new_password:"Xác nhận mật khẩu mới",
    passwords_not_match:"Mật khẩu chưa khớp",
    update_password:"Thay đổi mật khẩu",
    menu_about_us:"Về chúng tôi",
    refer:"Tham khảo",
    pending:"Chờ duyệt",
    approved:"Đã duyệt",
    signupFB:"Đăng nhập bằng Facebook",
    signupGG:"Đăng nhập bằng Google",
    signupEmail:"Đăng nhập bằng Email",
    or:"hoặc",
    signEmail:"Đăng ký bằng Email",
    haveAccount:"Đã có tài khoản",
    login:"Đăng nhập",
    loginFB:"Đăng nhập bằng Facebook",
    loginGG:"Đăng nhập bằng Google",
    forgotPW:"Quên mật khẩu",
    dhaveAccount:"Chưa có tài khoản",
    signup:"Đăng ký",
    signupwith:"Đăng ký bằng",
    bysignin:"Khi tích, Tôi đồng ý với PropertyPlus ",
    termofservice:"Hạn của dịch vụ ,",
    privacys:"Chính sách bảo mật ,",
    and:"và",
    copyright:"Bản Quyền",

    career:"Công việc",
    policy:"Chính sách",
    why_host:"Tại sao chủ nhà",
    hosting:"Hosting",
    community:"Trung tâm cộng đồng",
    terms:"Điều khoản",
    privacy:"Riêng tư",
    site_map:"Sơ đồ web",

    search_bar_livingHaNoi: "Sống ở Hà Nội thật dễ dàng",
    search_bar_price: "Giá nhà",
    search_bar_room: "Phòng",
    search_bar_area: "Diện tích",
    search_bar_facilities: "Hạ tầng",
}

var translationsEN = {
    search_bar_livingHaNoi: "Easy living in HaNoi",
    search_bar_price: "Price",
    search_bar_room: "Room",
    search_bar_area: "Area",
    search_bar_facilities: "Facilities",
    menu_support:"Support",
    menu_blog: "Blog",
    menu_about_us: "About us",
    menu_customer: "Support",
    menu_signup: "Sign up",
    menu_help: "Help",
    menu_login: "Login",
    menu_visit: "Your visit list",
    menu_host: "Become a host",
    btn_register: "Signup",
    blog_news:"News",
    blog_experience:"Experience",
    blog_tips:"Tips",
    blog_keyword:"Keyword",
    blog_search:"Search",
    blog_readmore:"READ MORE",
    blog_loadmore:"Load more",
    host_save:"Save",
    host_chooseyourapartment:"Choose your apartment",
    host_tenant:"tenant",
    host_overview:"Overview",
    host_problem:"Problem",
    host_describe:"Describe",
    host_information:"Information",
    host_photos:"Photos",
    host_location:"Location",
    host_time:"Time",
    host_billingdetail:"Billing Detail",
    host_property:"Property",
    host_article:"Article",
    host_datebilled:"Date Billed",
    host_amountbilled:"Amount Billed",
    host_paymentstatus:"Payment Status",
    host_detailcase:"Detail Case",
    host_calendar:"Calendar",
    host_downloadcontract:"Download Contract",
    host_name:"Name",
    host_type:"Type",
    host_project:"Project",
    host_nobedroom:"No.Bedroom",
    host_nobathroom:"No.Bathroom",
    host_area:"Area",
    host_address:"Address",
    host_enteralocation:"Enter a location",
    host_addbannerimage:"Add banner image",
    host_addanother:"Add another",
    host_thumbnail:"Thumbnail photo",
    host_banner:"banner photo",
    host_dragthepintoadjustitslocation:"Drag the pin to adjust its location",
    project_featureproject:"FEATURE PROJECT",
    project_onairproject:"ON-AIR PROJECT",
    project_explore:"Explore",
    project_seelist:"See list",
    project_upcomingproject:"UP-COMING PROJECT",

    price_range:"Price Range",
    clear:"Clear",
    rooms:"Rooms",
    bedrooms:"Bedrooms",
    bathrooms:"Bathrooms",
    area:"Area",
    facilities:"Facilities",
    introducing_property_plus:"Introducing Property Plus",
    explore_our_story:"Explore our story",
    see_how_our_service_is_best:"See how our service is best",
    standard_quality:"Standard Quality",
    fast_service:"Fast service",
    call_center:"24/7 call center",
    multi_language_support:"Multi-language support",
    explore_all_service:"Explore all service",
    choose_your_new_home:"Choose your new home",
    estimate_price:"Estimate Price",
    see_more:"See more",
    project_have_our_service:"Our projects",
    explore_all:"Explore all",
    show_map:"Show map",
    view_category:"VIEW",
    apartment_uppercase:"Apartment",
    night_text:"night",
    share_text:"Share",
    bookmark_text:"Favourite",
    about_this_listing:"ABOUT THIS LISTING",
    tour_this_home:"TOUR THIS HOME",
    living_room:"Living room",
    other_text:"Other",
    amenities:"AMENITIES",
    owner:"Owner",
    join_in:"Join in",
    estimate_price_included_service:"Estimate price included service",
    per_text:"per",
    apartment_price:"Apartment price",
    month_text:"month",
    service_total_price:"Service total price",
    service_package:"Service package",
    custom:"Custom",
    basic:"Basic",
    management_fee_by:"Management fee by PP",
    foreign_tv:"Foreign TV",
    laundry_cleaning:"Laundry & Cleaning",
    drinking_water:"Drinking water",
    detergent:"Detergent",
    toilet_paper:"toilet paper",
    electric_water_bill:"Electric & water bill",
    include_tax:"Include tax",
    send_visiting_request:"SEND VISITING REQUEST",
    similiar_listing:"SIMILAR LISTING",
    bookmark_uppercase:"Favourite",
    dashboard:"Dashboard",
    manage:"Manage",
    listing:"Listing",
    help:"Help",
    edit_profile:"Edit profile",
    account_setting:"Account setting",
    logout:"Log out",
    provide_information:"Provide information",
    upload_picture:"Upload picture",
    set_price:"Set price",
    verify:"Verify",
    congratulation_finish:"Congratulation, your apartment uploading is finish. It will be appear soon.",
    home:"Home",
    create_new:"Create new",
    row_1_step_1_1:"Let's get start listing your apartment",
    row_2_step_1_1:"What kind of place do you have?",    
    row_3_step_1_1:"Name your apartment's project",
    continue:"Continue",
    row_1_step_1_2:"Let's us know more about your apartment",
    row_2_step_1_2:"How many total bedroom your property have?",
    row_3_step_1_2:"How many total bathrooms your property have?",
    row_4_step_1_2:"How much area of your house",
    area_required:"Area is required",
    address_required:"Address is required",
    phone:"Phone",
    phone_required:"Phone is required",
    row_5_step_1_2:"Name your apartment ( Optional )",
    row_6_step_1_2:"Describe about your apartment ( Optional )",
    next:"Next",
    cancel:"Cancel",
    back:"Back",
    row_1_step_1_3:"Is the pin in  the right place?",
    row_2_step_1_3:"If needed, you can drag the pin to adjust its location.",
    add_banner_image:"Add banner image",
    great_progress:"Great progress",
    row_1_step_2_1:"Now let's get some details about your apartment then you can ready to publish your listing.",
    row_2_step_2_1:"Tips : Apartment have reality image help rentel make decision faster.",   
    add_another:"add another", 
    row_1_step_3_1:"Set up  price for your apartment",
    row_2_step_3_1:"Apartment management fee",
    row_3_step_3_1:"Similiar listing",
    row_1_step_3_2:"Choose your facilities",
    row_1_step_4_1:"To have a legal basis for doing business on PROPERTYPLUS, please post a photo or a scanned copy of the certificate of ownership of the land or a letter of authorization to use the property.",
    row_2_step_4_1:"- The upload size does not exceed 5MB.",
    row_3_step_4_1:"- The number of images per download does not exceed 5.",
    row_4_step_4_1:"Drag n drop or click to upload ",
    finish:"Finish",
    all:"All",
    listed:"Listed",
    description:"Description",
    listing_on_project:"LISTING ON PROJECT",
    general:"General",
    host_text:"Host",
    public_infomation:"Public infomation",
    full_name:"Full name",
    profile_photo:"Profile photo",
    row_1_edit_profile:"Clear frontal face photos are an important way for hosts and guests to learn about each other. Be sure to use a photo that clearly shows your face and doesn’t include any personal or sensitive info you’d rather not have landlord or tenant see.",
    upload_ava_text:"Upload a file from your device",
    private_infomation:"Private infomation",
    row_2_edit_profile:"We won't never share your private information with another Property Plus users.",
    i_am:"I am",
    birth_date:"Birth date",
    email:"Email",
    phone_number:"Phone number",
    verification:"Verification",
    row_3_edit_profile:"You'll need to provide indentification when you make a renting contract, so get a head by start by doing it now.",
    upload:"Upload",
    option_infomation:"Option infomation",
    company:"Company",
    company_address:"Company Address",
    row_4_edit_profile:"Give our Customer Service team a trusted contact we can alert in an urgent situation.",
    describe_yourself:"Describe Yourself",
    your_visiting_list:"Your visiting list",
    your_apartment:"Your apartment",
    visting_schedule:"Visiting schedule",
    visting_history:"Visiting history",
    you_visited:"You visited",
    apartment:"apartment",
    billing:"Billing",
    send_issue:"Send issue",
    your_using_service:"Your using service",
    service:"Service",
    quantity:"Quantity",
    maintance_management:"Maintance & management",
    default:"default",
    cable_tv:"Cable TV",
    times:"times",
    week:"week",
    bottles:"bottles",
    change:"Change",
    current_balance:"Current Balance",
    electricity_charge:"Electricity charge",
    not_paid:"Not paid",
    paid:"Paid",
    hot_water_charge:"Hot water charge",
    cold_water_charge:"Cold water charge",
    report_a_problem:"Report a problem",
    support_inbox:"Support Inbox",
    reported_billing_issue:"You reported a billing issue",
    last_update:"Last update",
    sending:"SENDING",
    solved:"SOLVED",
    in_progress:"IN PROGRESS",
    we_sent_you_a_message:"We sent you a message",
    rate_your_experience:"Rate your experience",
    change_your_password:"Change your password",
    old_password:"Old password",
    new_password:"New password",
    confirm_new_password:"Confirm new password",
    passwords_not_match:"Passwords does not match",
    update_password:"Update Password",
    refer:"Refer",
    pending:"Pending",
    approved:"Approved",
    signupFB:"Sign up with Facebook",
    signupGG:"Sign up with Google",
    signupEmail:"Sign up with Email",
    or:"or",
    signEmail:"Sign up with Email",
    haveAccount:"Already have an account",
    login:"Login",
    loginFB:"Log in with Facebook",
    loginGG:"Log in with Google",
    forgotPW:"Forgot password",
    dhaveAccount:"Don't have an account",
    signup:"Sign up",
    signupwith:"Sign up with",
    bysignin:"By sign up, I agree to PropertyPlus's ",
    termofservice:"Term of service ,",
    privacys:"Privacy policy ,",
    and:"and",
    copyright:"Copyright policy",

    career:"Career",
    policy:"Policy",
    why_host:"Why host",
    hosting:"Hosting",
    community:"Community center",
    terms:"Terms",
    privacy:"Privacy",
    site_map:"Site Map",
}

var translationsJP = {
    menu_about_us:"私たちについて",
    refer:"参照する",
    menu_customer: "サポート",
    menu_signup: "サインアップ",
    menu_support:"サポート",
    menu_blog: "ブログ",
    menu_about_us: "私たちに関しては",
    menu_help: "助けて",
    menu_login: "ログイン",
    menu_visit: "あなたの訪問リスト",
    menu_host: "ホストになる",

    btn_register: "サインアップ",
    blog_news:"ニュース",
    blog_experience:"経験",
    blog_tips:"ヒント",
    blog_keyword:"キーワード",
    blog_search:"サーチ",
    blog_readmore:"続きを読む",
    blog_loadmore:"もっと読み込む",
    host_save:"保存する",
    host_chooseyourapartment:"あなたのアパートを選択する",
    host_tenant:"テナント",
    host_overview:"概要",
    host_problem:"問題",
    host_describe:"説明する",
    host_information:"情報",
    host_photos:"写真",
    host_location:"ロケーション",
    host_time:"時間",
    host_billingdetail:"請求の詳細",
    host_property:"プロパティ",
    host_article:"記事",
    host_datebilled:"請求書日付",
    host_amountbilled:"請求額",
    host_paymentstatus:"支払い状況",
    host_detailcase:"詳細ケース",
    host_calendar:"カレンダー",
    host_downloadcontract:"契約をダウンロードする",
    host_name:"名",
    host_type:"タイプ",
    host_project:"プロジェクト",
    host_nobedroom:"ベッドルームの数",
    host_nobathroom:"バスルームの数",
    host_area:"エリア",
    host_address:"住所",
    host_enteralocation:"場所を入力してください",
    host_addbannerimage:"バナー画像を追加する",
    host_addanother:"別のものを追加する",
    host_thumbnail:"サムネイル写真",
    host_banner:"バナー写真",
    host_dragthepintoadjustitslocation:"ピンをドラッグして位置を調整する",
    project_featureproject:"フィーチャープロジェクト",
    project_onairproject:"オンエアプロジェクト",
    project_explore:"探検する",
    project_seelist:"リストを見る",
    project_upcomingproject:"アップ・アップ・プロジェクト",

    price_range:"価格帯",
    clear:"クリア",
    rooms:"部屋",
    bedrooms:"ベッドルーム",
    bathrooms:"バスルーム",
    area:"エリア",
    facilities:"施設",
    introducing_property_plus:"導入 Property Plus",
    explore_our_story:"私たちの物語を探る",
    see_how_our_service_is_best:"私たちのサービスがどのように最高のものかを見て",
    standard_quality:"標準品質",
    fast_service:"迅速なサービス",
    call_center:"24/7 コールセンター",
    multi_language_support:"多言語サポート",
    explore_all_service:"すべてのサービスを探索する",
    choose_your_new_home:"あなたの新しい家を選んでください",
    estimate_price:"見積価格",
    see_more:"続きを見る",
    project_have_our_service:"プロジェクトは私たちのサービスを持っている",
    explore_all:"すべてを見る",
    show_map:"地図を表示",
    view_category:"VIEW",
    apartment_uppercase:"アパート",
    night_text:"夜",
    share_text:"シェア",
    bookmark_text:"ブックマーク",
    about_this_listing:"このリストについて",
    tour_this_home:"このホームへ",
    living_room:"リビングルーム",
    other_text:"その他",
    amenities:"アメニティ",
    owner:"オーナー",
    join_in:"参加する",
    estimate_price_included_service:"見積価格に含まれるサービス",
    per_text:"〜ごと",
    apartment_price:"アパート価格",
    month_text:"月",
    service_total_price:"サービス合計金額",
    service_package:"サービスパッケージ",
    custom:"カスタム",
    basic:"ベーシック",
    management_fee_by:"PPによる管理手数料",
    foreign_tv:"外国のテレビ",
    laundry_cleaning:"ランドリー＆クリーニング",
    drinking_water:"水を飲んでいる",
    detergent:"洗剤",
    toilet_paper:"トイレットペーパー",
    electric_water_bill:"電気および水道料金",
    include_tax:"税金を含む",
    send_visiting_request:"訪問要請を送信する",
    similiar_listing:"同様のリスト",
    bookmark_uppercase:"ブックマーク",
    dashboard:"ガバナンス",
    manage:"管理",
    listing:"リスト",
    help:"助けて",
    edit_profile:"プロファイル編集",
    account_setting:"アカウントの設定",
    logout:"ログアウト",
    provide_information:"情報を提供する",
    upload_picture:"写真をアップロードする",
    set_price:"セット価格",
    verify:"確認",
    congratulation_finish:"おめでとう、アパートのアップロードは終了です。 すぐに表示されます。",
    home:"ホーム",
    create_new:"新しく作る",
    row_1_step_1_1:"あなたのアパートをリストアップしよう",
    row_2_step_1_1:"どのような場所がありますか？",    
    row_3_step_1_1:"アパートのプロジェクトに名前をつける",
    continue:"Continue",
    row_1_step_1_2:"あなたのアパートについてもっと知りましょう",
    row_2_step_1_2:"あなたの財産はどれくらいの合計寝室ですか？",
    row_3_step_1_2:"あなたの物件にはどれくらいの浴室がありますか？",
    row_4_step_1_2:"あなたの家のどのくらいの面積",
    area_required:"エリアが必要です",
    address_required:"アドレスは必須です",
    phone:"電話番号",
    phone_required:"電話番号は必須です",
    row_5_step_1_2:"あなたのアパートに名前を付けてください（オプション）",
    row_6_step_1_2:"アパートについての説明（オプション）",
    next:"次",
    cancel:"キャンセル",
    back:"バック",
    row_1_step_1_3:"ピンは正しい場所にありますか？",
    row_2_step_1_3:"必要に応じて、ピンをドラッグしてピンの位置を調整することができます。",
    add_banner_image:"バナー画像を追加する",
    great_progress:"大きな進歩",
    row_1_step_2_1:"次に、あなたのアパートについていくつかの詳細を聞いてみましょう。あなたはあなたのリストを公開する準備ができています。",
    row_2_step_2_1:"ヒント：アパートは現実のイメージを持っているので、レンタルは意思決定を速くします。",   
    add_another:"別のものを追加する", 
    row_1_step_3_1:"あなたのアパートの価格を設定する",
    row_2_step_3_1:"アパート管理手数料",
    row_3_step_3_1:"同様のリスト",
    row_1_step_3_2:"あなたの施設を選択してください",
    row_1_step_4_1:"PROPERTYPLUSでビジネスを行うための法的基盤を持つには、その土地の所有権証明書または使用許諾書の写真またはスキャンした写しを投稿してください。",
    row_2_step_4_1:"- アップロードサイズは5MBを超えません。",
    row_3_step_4_1:"- ダウンロードあたりの画像数は5を超えません。",
    row_4_step_4_1:"ドラッグアンドドロップ、またはクリックしてアップロード ",
    finish:"フィニッシュ",
    all:"すべて",
    listed:"リストされた",
    description:"説明",
    listing_on_project:"プロジェクト一覧",
    general:"一般",
    host_text:"ホスト",
    public_infomation:"公開情報",
    full_name:"フルネーム",
    profile_photo:"プロフィール写真",
    row_1_edit_profile:"正面顔写真をクリアすることは、ホストとゲストがお互いに学ぶ重要な方法です。 あなたの顔をはっきりと示す写真を必ず使用してください。個人または機密情報は含まれておらず、家主やテナントには見えません。",
    upload_ava_text:"デバイスからファイルをアップロードする",
    private_infomation:"個人情報",
    row_2_edit_profile:"私たちはあなたの個人情報を他のProperty Plusユーザーと共有することはありません。",
    i_am:"わたし",
    birth_date:"誕生日",
    email:"Email",
    phone_number:"電話番号",
    verification:"検証",
    row_3_edit_profile:"賃貸借契約を結ぶ際に身分証明書を提示する必要がありますので、今すぐ始めましょう。",
    upload:"アップロード",
    option_infomation:"オプション情報",
    company:"会社",
    company_address:"会社の住所",
    row_4_edit_profile:"緊急の状況で警告できる信頼できる連絡先を顧客サービスチームに提供します。",
    describe_yourself:"あなた自身について説明しなさい",
    your_visiting_list:"あなたの訪問リスト",
    your_apartment:"あなたのアパート",
    visting_schedule:"訪問予定",
    visting_history:"訪問履歴",
    you_visited:"あなたが訪問した",
    apartment:"アパート",
    billing:"請求書",
    send_issue:"問題を送信する",
    your_using_service:"あなたの使用しているサービス",
    service:"サービス",
    quantity:"量",
    maintance_management:"メンテナンスと管理",
    default:"デフォルト",
    cable_tv:"ケーブルテレビ",
    times:"回",
    week:"週間",
    bottles:"ボトル",
    change:"変化する",
    current_balance:"経常収支",
    electricity_charge:"電気料金",
    not_paid:"支払われない",
    paid:"Paid",
    hot_water_charge:"給湯",
    cold_water_charge:"冷水チャージ",
    report_a_problem:"問題を報告します",
    support_inbox:"サポート受信トレイ",
    reported_billing_issue:"請求の問題を報告しました",
    last_update:"最後の更新",
    sending:"送信",
    solved:"解決済み",
    in_progress:"進行中",
    we_sent_you_a_message:"私たちはあなたにメッセージを送った",
    rate_your_experience:"経験を評価する",
    change_your_password:"パスワードを変更してください",
    old_password:"以前のパスワード",
    new_password:"新しいパスワード",
    confirm_new_password:"新しいパスワードを確認",
    passwords_not_match:"パスワードが一致しません",
    update_password:"パスワードの更新",
    pending:"保留中の承認",
    approved:"レビュー済み",
    signupFB:"に登録する Facebook",
    signupGG:"に登録する Google",
    signupEmail:"に登録する Email",
    or:"または",
    signEmail:"登録者 Email",
    haveAccount:"すでにアカウントがあります",
    login:"サインイン",
    loginFB:"にログインする Facebook",
    loginGG:"にログインする Google",
    forgotPW:"パスワードを忘れました",
    dhaveAccount:"まだアカウントがありません",
    signup:"サインアップ",
    signupwith:"登録者",
    bysignin:"サインアップすることで、私は同意します PropertyPlus ",
    termofservice:"任期 ,",
    privacys:"プライバシーポリシー ,",
    and:"と",
    copyright:"著作権",

    career:"キャリア",
    policy:"ポリシー",
    why_host:"なぜ宿主ですか？",
    hosting:"ホスティング",
    community:"コミュニティセンター",
    terms:"条項",
    privacy:"プライバシー",
    site_map:"サイトマップ",

    search_bar_livingHaNoi: "HaNoi での簡単な生活",
    search_bar_price: "価格",
    search_bar_room: "ルーム",
    search_bar_area: "エリア",
    search_bar_facilities: "施設",

}

app.config(['$translateProvider', function ($translateProvider) {
    // add translation tables
    $translateProvider.translations('en', translationsEN);
    $translateProvider.translations('vi', translationsVI);
    $translateProvider.translations('jp', translationsJP);
    $translateProvider.preferredLanguage('en');
    $translateProvider.fallbackLanguage('vi');
    $translateProvider.fallbackLanguage('jp');
}]);