var translationsVI = {
    menu_customer: "Hỗ trợ",
    menu_signup: "Đăng ký",
    menu_support:"Hỗ trợ",
    menu_blog: "Blog",
    menu_about_us: "Câu chuyện của Property Plus",
    menu_help: "Trợ giúp",
    menu_login: "Đăng nhập",
    menu_visit: "Danh sách nhà thăm",
    menu_host: "Chủ nhà",
    btn_register: "Đăng ký",
    blog_news:"Tin Tức",
    blog_experience:"Kinh Nghiệm",
    blog_tips:"Lời Khuyên",
    blog_keyword:"Từ khóa",
    blog_search:"Tìm kiếm",
    blog_readmore:"ĐỌC TIẾP",
    blog_loadmore:"Xem thêm",
    host_save:"Lưu",
    host_chooseyourapartment:"Chọn căn hộ của bạn",
    host_tenant:"Người thuê nhà",
    host_overview:"Tổng quan",
    host_problem:"Vấn đề",
    host_describe:"Miêu tả",
    host_information:"Thông tin",
    host_photos:"Ảnh",
    host_location:"Vị trí",
    host_time:"Thời gian",
    host_billingdetail:"Chi tiết thanh toán",
    host_property:"Bất động sản",
    host_article:"Vật phẩm",
    host_datebilled:"Ngày lập hóa đơn",
    host_amountbilled:"Chi phí",
    host_paymentstatus:"Thanh toán",
    host_detailcase:"Chi tiết các trường hợp",
    host_calendar:"Lịch",
    host_downloadcontract:"Tải hợp đồng",
    host_name:"Tên",
    host_type:"Loại",
    host_project:"Dự án",
    host_nobedroom:"Số phòng ngủ",
    host_nobathroom:"Số phòng tắm",
    host_area:"Diện tích",
    host_address:"Địa chỉ",
    host_enteralocation:"Nhập địa chỉ",
    host_addbannerimage:"Thêm ảnh",
    host_addanother:"Thêm ảnh",
    host_thumbnail:"Ảnh thu nhỏ",
    host_banner:"-ảnh biểu ngữ",
    host_dragthepintoadjustitslocation:"Kéo ghim để điều chỉnh vị trí của nó",
    project_featureproject:"CÁC ĐẶC TRƯNG CỦA DỰ ÁN",
    project_onairproject:"DỰ ÁN ĐANG TRIỂN KHAI",
    project_explore:"Khám phá",
    project_seelist:"Xem danh sách",
    project_upcomingproject:"DỰ ÁN SẮP TRIỂN KHAI",


    price_range:"Phạm vi giá",
    clear:"Làm mới",
    rooms:"Các phòng",
    bedrooms:"Phòng ngủ",
    bathrooms:"Phòng tắm",
    area:"Diện tích",
    facilities:"Cơ sở vật chất",
    introducing_property_plus:"Giới thiệu Property Plus",
    explore_our_story:"Về chúng tôi",
    see_how_our_service_is_best:"Các dịch vụ tốt nhất của chúng tôi",
    standard_quality:"Tiêu chuẩn chất lượng",
    fast_service:"Dịch vụ nhanh",
    call_center:"Trung tâm cuộc gọi 24/7",
    multi_language_support:"Hỗ trợ đa ngôn ngữ",
    explore_all_service:"Về các dịch vụ",
    choose_your_new_home:"Chọn nhà mới của bạn",
    estimate_price:"Giá ước tính",
    see_more:"Xem thêm",
    project_have_our_service:"Dự án có dịch vụ của chúng tôi",
    explore_all:"Xem tất cả",
    show_map:"Hiện bản đồ",
    view_category:"KIỂU XEM",
    apartment_uppercase:"Căn hộ",
    night_text:"đêm",
    share_text:"Chia sẻ",
    bookmark_text:"Đã lưu",
    about_this_listing:"VỀ DANH SÁCH NÀY",
    tour_this_home:"THĂM QUAN NHÀ",
    living_room:"Phòng khách",
    other_text:"Khác",
    amenities:"TIỆN NGHI",
    owner:"Chủ sở hữu",
    join_in:"Tham gia từ",
    estimate_price_included_service:"Giá ước tính bao gồm dịch vụ",
    per_text:"mỗi",
    apartment_price:"Giá căn hộ",
    month_text:"tháng",
    service_total_price:"Tổng giá dịch vụ",
    service_package:"Gói dịch vụ",
    custom:"Tùy chọn",
    basic:"Cơ bản",
    management_fee_by:"Phí quản lý bởi PP",
    foreign_tv:"TV Nước ngoài",
    laundry_cleaning:"Giặt là",
    drinking_water:"Nước uống",
    detergent:"Chất tẩy rửa",
    toilet_paper:"giấy vệ sinh",
    electric_water_bill:"Hóa đơn điện và nước",
    include_tax:"Bao gồm thuế",
    send_visiting_request:"GỬI YÊU CẦU LỊCH HẸN",
    similiar_listing:"DANH SÁCH TƯƠNG TỰ",
    bookmark_uppercase:"ĐÃ LƯU",
    dashboard:"Quản trị",
    manage:"Quản lý",
    listing:"Danh sách",
    help:"Hỗ trợ",
    edit_profile:"Chỉnh sửa hồ sơ",
    account_setting:"Cài đặt tài khoản",
    logout:"Thoát",
    provide_information:"Cung cấp thông tin",
    upload_picture:"Tải ảnh",
    set_price:"Đặt giá",
    verify:"Kiểm chứng",
    congratulation_finish:"Xin chúc mừng, việc tải lên căn hộ của bạn đã kết thúc. Nó sẽ sớm xuất hiện.",
    home:"Trang chủ",
    create_new:"Tạo mới",
    row_1_step_1_1:"Hãy bắt đầu liệt kê căn hộ của bạn",
    row_2_step_1_1:"Bạn có loại bất động sản nào?",    
    row_3_step_1_1:"Tên dự án của bạn",
    continue:"Tiếp tục",
    row_1_step_1_2:"Hãy cho chúng tôi biết thêm về căn hộ của bạn",
    row_2_step_1_2:"Tổng số phòng ngủ của căn hộ sở hữu ?",
    row_3_step_1_2:"Tổng số phòng tắm của căn hộ sở hữu ?",
    row_4_step_1_2:"Diện tích của căn hộ",
    area_required:"Diện tích không được bỏ trống",
    address_required:"Địa chỉ chưa đúng định dạng",
    phone:"Số điện thoại",
    phone_required:"Số điện thoại chưa đúng định dạng",
    row_5_step_1_2:"Tên căn hộ ( Không bắt buộc )",
    row_6_step_1_2:"Mô tả về căn hộ ( Không bắt buộc )",
    next:"Tiếp theo",
    cancel:"Hủy",
    back:"Quay lại",
    row_1_step_1_3:"Đây có đúng là vị trí căn hộ của bạn?",
    row_2_step_1_3:"Nếu cần, bạn có thể kéo ghim để điều chỉnh vị trí của nó.",
    add_banner_image:"Thêm ảnh bìa",
    great_progress:"Tiến độ tuyệt vời!",
    row_1_step_2_1:"Bây giờ chúng ta hãy lấy một số chi tiết về căn hộ của bạn sau đó bạn có thể sẵn sàng để xuất bản danh sách của bạn.",
    row_2_step_2_1:"Lời khuyên: Căn hộ có hình ảnh thực tế giúp cho thuê quyết định nhanh hơn.",   
    add_another:"Tải ảnh khác", 
    row_1_step_3_1:"Thiết lập giá cho căn hộ của bạn",
    row_2_step_3_1:"Phí quản lý căn hộ",
    row_3_step_3_1:"Căn hộ tương tự",
    row_1_step_3_2:"Chọn cơ sở vật chất của căn hộ",
    row_1_step_4_1:"Để có cơ sở pháp lý để kinh doanh trên PROPERTYPLUS, vui lòng đăng ảnh hoặc bản sao chụp giấy chứng nhận quyền sở hữu đất hoặc thư ủy quyền sử dụng tài sản.",
    row_2_step_4_1:"- Không upload ảnh dung lượng quá 5mb.",
    row_3_step_4_1:"- Số lượng ảnh upload không vượt quá 5.",
    row_4_step_4_1:"Kéo hoặc thả để tải ảnh lên ",
    finish:"Hoàn thành",
    all:"Tất cả",
    listed:"Liệt kê",
    description:"Mô tả",
    listing_on_project:"DANH SÁCH DỰ ÁN",
    general:"Cài đặt chung",
    host_text:"Chủ nhà",
    public_infomation:"Thông tin công khai",
    full_name:"Tên đầy đủ",
    profile_photo:"Ảnh đại diện",
    row_1_edit_profile:"Hình ảnh mặt trước rõ ràng là một cách quan trọng để chủ và khách tìm hiểu về nhau. Hãy chắc chắn sử dụng ảnh hiển thị rõ ràng khuôn mặt của bạn và không bao gồm bất kỳ thông tin cá nhân hoặc nhạy cảm nào mà bạn không muốn chủ nhà hoặc người thuê xem thấy.",
    upload_ava_text:"Tải lên một ảnh",
    private_infomation:"Thông tin riêng tư",
    row_2_edit_profile:"Chúng tôi sẽ không bao giờ chia sẻ thông tin cá nhân của bạn với người dùng Property Plus khác.",
    i_am:"Tôi là",
    birth_date:"Ngày sinh",
    email:"Email",
    phone_number:"Số điện thoại",
    verification:"Xác minh",
    row_3_edit_profile:"Bạn sẽ cần cung cấp thông tin nhận dạng khi bạn thực hiện hợp đồng thuê, vì vậy hãy bắt đầu bằng cách thực hiện ngay bây giờ.",
    upload:"Tải lên",
    option_infomation:"Thông tin tùy chọn",
    company:"Công ty",
    company_address:"Địa chỉ công ty",
    row_4_edit_profile:"Cung cấp cho nhóm Dịch vụ khách hàng của chúng tôi một liên hệ đáng tin cậy mà chúng tôi có thể cảnh báo trong tình huống khẩn cấp.",
    describe_yourself:"Mô tả về bản thân",
    your_visiting_list:"Danh sách lịch hẹn của bạn",
    your_apartment:"Căn hộ của bạn",
    visting_schedule:"Lịch hẹn",
    visting_history:"Lịch sử hẹn",
    you_visited:"Bạn đã thăm",
    apartment:"căn hộ",
    billing:"Thanh toán",
    send_issue:"Gửi sự cố",
    your_using_service:"Bạn đang sử dụng dịch vụ",
    service:"Dịch vụ",
    quantity:"Số lượng",
    maintance_management:"Quản lý và bảo trì",
    default:"mặc định",
    cable_tv:"Cáp TV",
    times:"lần",
    week:"tuần",
    bottles:"bình",
    change:"Thay đổi",
    current_balance:"Số dư hiện tại",
    electricity_charge:"Tiền điện",
    not_paid:"Chưa thanh toán",
    paid:"Đã thanh toán",
    hot_water_charge:"Phí nước nóng",
    cold_water_charge:"Phí nước lạnh",
    report_a_problem:"Báo cáo sự cố",
    support_inbox:"Hòm thư hỗ trợ",
    reported_billing_issue:"Bạn đã báo cáo sự cố thanh toán",
    last_update:"Cập nhật cuối cùng",
    sending:"ĐANG GỬI",
    solved:"ĐÃ GIẢI QUYẾT",
    in_progress:"TRONG TIẾN TRÌNH",
    we_sent_you_a_message:"Chúng tôi gửi cho bạn 1 tin nhắn",
    rate_your_experience:"Đánh giá của bạn",
    change_your_password:"Thay đổi mật khẩu",
    old_password:"Mật khẩu cũ",
    new_password:"Mật khẩu mới",
    confirm_new_password:"Xác nhận mật khẩu mới",
    passwords_not_match:"Mật khẩu chưa khớp",
    update_password:"Thay đổi mật khẩu",
    refer:"Tham khảo",
    pending:"Chờ duyệt",
    approved:"Đã duyệt",
    signupFB:"Đăng nhập bằng Facebook",
    signupGG:"Đăng nhập bằng Google",
    signupEmail:"Đăng nhập bằng Email",
    or:"hoặc",
    signEmail:"Đăng ký bằng Email",
    haveAccount:"Đã có tài khoản",
    login:"Đăng nhập",
    loginFB:"Đăng nhập bằng Facebook",
    loginGG:"Đăng nhập bằng Google",
    forgotPW:"Quên mật khẩu",
    dhaveAccount:"Chưa có tài khoản",
    signup:"Đăng ký",
    signupwith:"Đăng ký bằng",
    bysignin:"Khi tích, Tôi đồng ý với PropertyPlus ",
    termofservice:"Hạn của dịch vụ ,",
    privacys:"Chính sách bảo mật ,",
    and:"và",
    copyright:"Bản Quyền",

    career:"Công việc",
    policy:"Chính sách",
    why_host:"Tại sao chủ nhà",
    hosting:"Hosting",
    community:"Trung tâm cộng đồng",
    terms:"Điều khoản",
    privacy:"Riêng tư",
    site_map:"Sơ đồ web",

    search_bar_livingHaNoi: "Sống ở Hà Nội thật dễ dàng",
    search_bar_price: "Giá nhà",
    search_bar_room: "Phòng",
    search_bar_area: "Diện tích",
    search_bar_facilities: "Hạ tầng",

    technology:"CÔNG NGHỆ",
    besides:"Không chỉ dừng lại ở các dịch vụ như trên, PP không dừng nỗ lực phát triển để đem lại sự tiện lợi tuyệt đối cho khách hàng. Chúng tôi đã áp dụng hàng loạt giải pháp công nghệ tiên tiến cho mỗi quá trình.",
    From:"PROPERTY PLUS sử dụng công nghệ thực tế ảo và mô hình 3D, Matterport, cung cấp phối cảnh căn hộ chính xác nhất để bạn có thể xem căn hộ mà không cần đi đến tận nơi. Và chúng tôi đảm bảo, những gì bạn thấy là thật.",
    canbe:"PROPERTY PLUS sử dụng công nghệ thực tế ảo và mô hình 3D, Matterport, cung cấp phối cảnh căn hộ chính xác nhất để bạn có thể xem căn hộ mà không cần đi đến tận nơi. Và chúng tôi đảm bảo, những gì bạn thấy là thật.",
    screen:"Từ khâu xem nhà, làm hợp đồng cho đến giám sát nhà, bạn có thể cách xa Hà Nội nửa vòng trái đất và làm tất cả qua màn hình thiết bị thông minh. ",
    
    sv_house:"Ban Buồng Phòng",
    sv_5star:"Dịch vụ tiêu chuẩn 5 sao",
    sv_beinghonest:"Là những nhân viên dày dặn kinh nghiệm được đào tạo bài bản và từng làm việc tại các môi trường chuyên nghiệp đòi hỏi tính trung thực cao, đội ngũ nhân viên buồng phòng của PROPERTY PLUS tự tin có thể làm hài lòng cả những vị khách khó tính nhất",
    sv_procedure:"QUY TRÌNH",
    sv_standard:"Quy trình tiêu chuẩn được thiết kế bởi các chuyên gia phục vụ các khách sạn Quốc tế 5 sao. ",
    sv_trust:"TIN CẬY",
    sv_withour:"Trung thực và thân thiện, khách hàng của PROPERTY PLUS có thể hoàn toàn an tâm khi vắng nhà.",
    sv_experience:"KINH NGHIỆM",
    sv_beingable:"Xử lí các nghiệp vụ mang tính chuyên nghiệp một cách nhanh gọn và cởi mở.",
    sv_tool:"DỤNG CỤ",
    sv_tools:"Sử dụng các dụng cụ, hóa chất đã được kiểm duyệt để đảm bảo chất lượng và an toàn cho con người, tài sản, và môi trường. ",
    sv_technique:"Bảo trì kỹ thuật",
    sv_beingalways:"Sẵn sàn vì khách hàng",
    sv_devoting:"“Tận tâm cống hiến” là tôn chỉ hoạt động của những kỹ thuật viên bảo trì chỉ có tại PROPERTY PLUS. Chúng tôi luôn sẵn sàng có mặt để hỗ trợ, giải quyết các vấn đề đảm bảo chất lượng cuộc sống của khách hàng. ",
    sv_speed:"TỐC ĐỘ",
    sv_presenting:"Có mặt tận nơi để khảo sát, xử lí nhanh gọn trong vòng 120 phút kể từ lúc",
    sv_reception:"tiếp nhận thông tin từ khách hàng",
    sv_responsibility:"TRÁCH NHIỆM",
    sv_beingableto:"Đặt lợi ích của khách hàng lên đầu, nỗ lực cố gắng xử lí nhanh chóng ",
    sv_professionalway:"và chuyên nghiệp.",
    sv_management:"Quản lý",
    sv_resolution:"Xử lý chuyên nghiệp",
    sv_through:"Chỉ với một đường dây nóng phục vụ 24/7, mọi vấn đề của khách hàng sẽ được bàn giao tới các ban liên quan.",
    sv_communication:"NGÔN NGỮ",
    sv_three:"Ba ngôn ngữ thông dụng trong giao tiếp: tiếng Anh, tiếng Nhật và tiếng Việt. ",
    sv_availability:"SẴN SÀNG",
    sv_availableto:"Luôn sẵn sàng hỗ trợ và tiếp nhận các phản hồi từ khách hàng 24/7.",
    sv_attitude:"THÁI ĐỘ",
    sv_working:"Làm việc bằng cả tấm lòng, chủ động lắng nghe, vui vẻ tiếp nhận phản hồi và khiếu nại từ khách hàng trong bất cứ trường hợp nào.",
    
    ab_general:"Chung",
    ab_organization:"Cấu trúc tổ chức",
    ab_company:"Mô hình công ty",
    ab_history:"LỊCH SỬ HÌNH THÀNH VÀ PHÁT TRIỂN",
    ab_vision:"TẦM NHÌN VÀ NHIỆM VỤ",
    ab_core:"NHỮNG GIÁ TRỊ CỐT LÕI",
    ab_development:"ĐỊNH HƯỚNG PHÁT TRIỂN",
    ab_taking:"Được thành lập năm 2011, PROPERTY PLUS tự hào là 1 trong 3 đơn vị lớn nhất trong lĩnh vực tư vấn, kinh doanh và cho thuê bất động sản cao cấp tại Hà Nội.Bước đầu xâm nhập vào thị trường cho thuê căn hộ, Đại Lợi luôn trăn trở về các giá trị bất động sản cao cấp của Việt Nam và việc hỗ trợ tốt hơn cho đời sống của thương nhân người nước ngoài công tác tại Hà Nội nói riêng và Việt Nam nói chung. Nhận thấy được sự thiếu sót trong vấn đề môi giới căn hộ cao cấp, Đại Lợi thành lập PROPERTY PLUS, đưa việc cung cấp dịch vụ tiêu chuẩn chuyên nghiệp cho khách đến làm việc và sinh sống tại Việt Nam làm mục tiêu hàng đầu.  Để đáp ứng được nhu cầu về cuộc sống của những người nước ngoài công tác và sinh sống tại Việt Nam, chúng tôi luôn nỗ lực cung cấp, bổ sung các dịch vụ giá trị gia tăng nhằm mục đích gia tăng giá trị căn hộ. Với hệ thống chăm sóc và quản lý căn hộ, PROPERTY PLUS đã và đang giải quyết những khó khăn của khách hàng trong việc tiếp cận các căn hộ cao cấp thuộc sở hữu cá nhân. Hơn thế nữa, khách hàng sẽ được tận hưởng cuộc sống trong cơ sở hạ tầng sang trọng và tiện ích đẳng cấp, với đội ngũ nhân viên - kỹ thuật viên nhiều kinh nghiệm, nhiệt tình và được đào tạo chuyên nghiệp. Nhiệm vụ của chúng tôi là đưa yếu tố của sự thoải mái, dễ dàng và thân thiện vào cuộc sống của khách hàng. Mọi vấn đề phát sinh trong cuộc sống thường nhật sẽ đều do chúng tôi giải quyết. Với kinh nghiệm quản lí gần 200 khách hàng hiện tại đến từ nhiều quốc gia khách nhau, kết hợp với sự phát triển vượt bậc của công nghệ, PROPERTY PLUS hướng đến sự tối ưu hóa thị trường bất động sản nhà ở cho chủ nhà và khách thuê. Chủ nhà có thể nhanh chóng cho thuê được các bất động sản cao cấp với mức giá mong muốn. Khách thuê nhà có thể dễ dàng tiếp cận với tất cả các bất động sản cao cấp đi kèm với dịch vụ tiêu chuẩn.",
    ab_vis:"TẦM NHÌN :",
    ab_market:"Với mong muốn thay đổi cách nhìn nhận của khách hàng quốc tế về dịch vụ cung cấp bởi người Việt Nam, với khát vọng tiên phong, PROPERTY PLUS hướng tới vị trí đơn vị dẫn đầu trong thị trường bất động sản dành cho người nước ngoài tại Việt Nam với những dịch vụ mang đẳng cấp của thế giới.",
    ab_mission:"SỨ MỆNH :",
    ab_concerned:"Chúng tôi có sứ mệnh giúp chủ nhà cá nhân và khách nước ngoài thuê nhà có thể thoải mái tận hưởng cuộc sống mà không phải bận tâm đến bất cứ vấn đề quản lí nhà đất thường nhật cũng như các vấn đề liên quan.",
    ab_cor:"GIÁ TRỊ CỐT LÕI",
    ab_isalways:"Nền móng của PROPERTY PLUS được xây dựng dựa trên những mối quan hệ với nhà đầu tư, đối tác, khách hàng, người lao động và cả xã hội, PROPERTY PLUS hiểu rằng đó là những gì quý giá nhất đối với mỗi doanh nghiệp. PROPERTY PLUS luôn cam kết để giữ vững các giá trị cũng như củng cố những mối quan hệ đó.",
    ab_creativity:"1. SÁNG TẠO: Luôn đổi mới, cải tiến và phát triển. Nâng cao tinh thần “dám nghĩ dám làm”",
    ab_commit:"2. TIN CẬY: Nỗ lực hết mình để đảm bảo thực hiện đúng và cao hơn các cam kết đặt ra.",
    ab_orientation:"3. ĐỊNH HƯỚNG: Khát vọng tiên phong tạo ra những xu thế mới.",
    ab_conscientious:"4. TẬN TÂM: Chăm sóc khách hàng bằng sự tự nguyện và hào hứng từ trái tim.",
    ab_cooperation:"5. HỢP TÁC: Trân trọng các mối quan hệ với khách hàng, đối tác, đồng nghiệp, nhà đầu tư và toàn thể xã hội.",
    ab_minh:"Với những thuận lợi và định hướng phát triển hiển tại, PROPERTY PLUS đặt mục tiêu trở thành nền tảng lớn nhất Việt Nam về kết nối chủ nhà và khách thuê nhà dài hạn trong vòng 5 năm tới, với kỳ vọng mở rộng quỹ căn lên con số 15.000, chiếm 5% tổng số căn hộ cao cấp tại Việt Nam và có mặt tại các thành phố lớn như Hà Nội, Hồ Chí Minh, Đà Nẵng, Hải Phòng, Nhà Trang, …",
    abu_business:"MÔ HÌNH KINH DOANH",
    abu_tenants:"QUYỀN LỢI CỦA NGƯỜI THUÊ NHÀ",
    abu_landlord:"QUYỀN LỢI CỦA CHỦ NHÀ",
    abu_friendly:"Bất động sản Plus Plus để xây dựng một mô hình tích hợp vừa phức tạp vừa thân thiện với người dùng cho mỗi người thụ hưởng của cộng đồng chúng ta.",
    abu_butle:"Chuyên dụng Butle",
    abu_large:"•    Tận hưởng đời sống đạt tiêu chuẩn chất lượng cao với mức giá hợp lí. ",
    abu_reception:"•  Ban quản lý và lễ tân chuyên nghiệp và tận tình. ",
    abu_good:"• Vị trí thuận lợi và cơ sở vật chất hoàn thiện như gym, bể bơi,...",
    abu_star:"• Dịch vụ quản gia đạt chuẩn 5 sao",
    abu_periodic:"• Đội ngũ kỹ thuật được đào tạo và tuyển dụng kĩ lưỡng theo chuẩn đầu vào của PROPERTY PLUS.",
    abu_procedural:"•   Hỗ trợ về các thủ tục nhà đất: hợp đồng thuê nhà online, thuế, hóa đơn dịch vụ,…",
    abu_security:"• An toàn phòng chống cháy nổ, an toàn về các vấn đề xã hội, dân trí cao, dùng mã QR bảo mật căn hộ. Thiết bị và đội ngũ an ninh được bảo đảm hơn tại các khu chung cư cao cấp bậc nhất.",
    abu_discover:"• Khám phá và hòa nhập vào cuộc sống và môi trường văn hóa bản địa.",
    abu_house:"Quản lý nhà chuyên nghiệp",
    abu_pp:"PP sở hữu đội ngũ chuyên viên môi giới chuyên nghiệp và am hiểu thị trường bất động sản tại Việt Nam, qua đó giúp căn hộ của bạn được tiếp cận một cách hiệu quả đến nhiều khách hàng tiềm năng trong thời gian ngắn nhất. Chúng tôi sẽ sắp xếp tất cả các công việc liên quan đến giấy tờ và quản lí căn hộ.",
    abu_dedicated:"•    Đội ngũ tư vấn phục vụ 24/7: tận tình, chuyên nghiệp, am hiểu thị trường.",
    abu_marketing:"•    Quảng cáo, tiếp thị truyền thông trên các kênh.",
    abu_optimizing:"•   Tối ưu hóa thời gian trống bằng dịch vụ cho thuê ngắn hạn.",
    abu_procedural:"•   Hỗ trợ về các thủ tục nhà đất: hợp đồng cho thuê, thuế, hóa đơn dịch vụ,…",
    abu_standard:"• Dịch vụ quản gia đạt chuẩn 5 sao",
    abu_periodic:"• Đội ngũ kỹ thuật được đào tạo và tuyển dụng kĩ lưỡng theo chuẩn đầu vào của PROPERTY PLUS.",
    abu_free:"• Hỗ trợ 3 triệu đồng/ năm tiền bảo trì, bảo dưỡng căn hộ.",
    abu_security:"• Bảo đảm an ninh: sử dụng mã QR và phần mềm quản lí căn hộ. ",
    abu_parties:"•  Trao đổi thông tin tường tận giữa các bên về các thủ tục cần thiết.",
    ab_team:"ĐỘI NGŨ CỦA CHÚNG TÔI",
    ab_ceo:"Giám đốc điều hành và người sáng lập",
    ab_staff:"NHÂN VIÊN XUẤT SẮC",

    our_technology:"Công nghệ của chúng tôi",
    apartment_searching_platform:"Nền tảng tìm kiếm căn hộ",
    mutil_party_communication_system:"Hệ thống truyền thông đa đảng",
    service_and_management_system:"Dịch vụ và hệ thống quản lý",
    customer_realationship_management_system:"Hệ thống quản lý quan hệ khách hàng",
    explore_our_tech:"Khám phá thêm",  

    
    content_about_us:"<p>Từ sâu trong trái tim, chúng tôi tin rằng, an cư lập nghiệp tại một đất nước mới nên là trải nghiệm tuyệt vời, đáng nhớ, và Property Plus luôn cố gắng đem đến cho những người bạn Quốc tế không gian sống đầy tiện nghi, sang trọng, thoải mái và cảm giác được đón chào ngay từ khoảnh khắc bước chân qua cánh cửa.</p> "+
                    "<p>Tại Property Plus, bạn có thể:</p>"+
                    "<p>Tận hưởng cuộc sống trong cơ sở hạ tầng sang trọng và tiện ích đẳng cấp với chi phí hợp lý.</p>"+
                    "<p>Đội ngũ nhân viên - kỹ thuật viên nhiều kinh nghiệm, nhiệt tình và được đào tạo chuyên nghiệp theo tiêu chuẩn 5 sao.</p>"+
                    "<p>Trải nghiệm cá nhân với không gian và dịch vụ phù hợp nhất với bạn. </p>"+
                    "<p>Dịch vụ với đội ngũ nhân viên - kỹ thuật viên nhiều kinh nghiệm, nhiệt tình và được đào tạo chuyên nghiệp theo tiêu chuẩn 5 sao.</p>"+
                    "<p>Cân bằng cuộc sống giữa công việc và hưởng thụ.</p>",

    po_policy:"CHÍNH SÁCH QUYỀN RIÊNG TƯ",
    po_propertyplus:"Công ty Trách nhiệm Hữu hạn Thương Mại và Tư vấn Bất Động Sản Đại Lợi sở hữu thương hiệu Property Plus và điều hành trang web propertyplus.com.vn. Chính Sách Quyền Riêng Tư này mô tả cách thức chúng tôi thu thập, sử dụng, tiết lộ, xử lý và bảo vệ thông tin nhận dạng cá nhân (“Dữ Liệu Cá Nhân”) mà Quý vị (“Người dùng”) có thể cung cấp liên quan đến các dịch vụ của Property Plus được cung cấp thông qua trang web: www.propertyplus.com (“Trang Web”). Dữ Liệu Cá Nhân có nghĩa là dữ liệu, cho dù là đúng hoặc không đúng, về một cá nhân có thể được nhận dạng từ dữ liệu đó, hoặc từ dữ liệu và các thông tin khác mà Property Plus có được hoặc có quyền truy cập. Các đề cập Trang Web được coi là bao gồm cả các trang phái sinh, bao gồm nhưng không giới hạn ở các trang web và ứng dụng di động của Trang Web. Bằng cách truy cập hoặc sử dụng Trang Web, Quý vị đồng ý và chấp thuận việc thu thập, sử dụng, tiết lộ và xử lý Dữ Liệu Cá Nhân của Quý vị theo Chính Sách Quyền Riêng Tư này và/hoặc Điều Khoản Trang Web. ",
    po_fromtime:"Tùy từng thời điểm, Property Plus có thể sửa đổi Chính Sách Quyền Riêng Tư để tương thích với những thay đổi về pháp luật, các thực tiễn thu thập và sử dụng Dữ Liệu Cá Nhân của chúng tôi, các tính năng của Trang Web, hoặc những tiến bộ về công nghệ. Nếu chúng tôi thực hiện các sửa đổi mà làm thay đổi cách thức chúng tôi thu thập hoặc sử dụng Dữ Liệu Cá Nhân của Quý vị, thì những sửa đổi đó sẽ được đăng trong Chính Sách Quyền Riêng Tư này và ngày có hiệu lực sẽ được nêu ở ngay phần đầu của Chính Sách Quyền Riêng Tư này. Vì vậy, Quý vị nên xem một cách định kỳ Chính Sách Quyền Riêng Tư này để được cập nhật về các chính sách và thực tiễn hiện hành của chúng tôi. Property Plus cũng sẽ đăng nổi bật những thay đổi quan trọng như vậy trước khi áp dụng các thay đổi. Nếu Quý vị không đồng ý với bất kỳ thay đổi hoặc sửa đổi nào trong Chính Sách Quyền Riêng Tư, xin vui lòng không tiếp tục sử dụng Trang Web. Quý vị sẽ được xem như đã đồng ý với bất kỳ sự sửa đổi của Chính Sách Quyền Riêng Tư khi Quý vị sử dụng Trang Web sau ngày có hiệu lực của sửa đổi đó.",
    po_collect:"1. Thông Tin Chúng Tôi Thu Thập",
    po_we:"Chúng tôi thu thập Dữ Liệu Cá Nhân về Quý vị mà Quý vị cung cấp cho chúng tôi khi sử dụng Trang Web. Dữ Liệu Cá Nhân này bao gồm nhưng không giới hạn ở tên, thông tin nhận dạng Người Dùng Property Plus và thông tin đăng nhập, địa chỉ, số điện thoại, địa chỉ email, tên dự án, vị trí dự án và/hoặc thời gian lưu trú của Quý vị. Chúng tôi cũng thu thập thông tin không nhận dạng cá nhân (thông tin không thể sử dụng để nhận dạng Quý vị), bao gồm nhưng không giới hạn ở địa chỉ IP, dữ liệu về vị trí địa lý, loại hệ điều hành, quốc tịch, ưu tiên tìm kiếm, cũng như dữ liệu liên quan đến việc sử dụng Internet nói chung.",
    po_howwe:"2. Chúng Tôi Sử Dụng Thông Tin Của Quý vị Như Thế Nào",
    po_wemay:"Chúng tôi có thể sử dụng Dữ Liệu Cá Nhân của Quý vị và các thông tin khác thu thập qua Trang Web, cho các mục đích sau:",
    po_registering:"•   Đăng ký, quản lý và/hoặc quản trị việc Quý vị sử dụng và/hoặc truy cập Trang Web;",
    po_managing:"•  Quản lý, điều hành, quản trị và cung cấp cho Quý vị các dịch vụ được đề nghị trên Trang Web;",
    po_contacting:"•    Để liên hệ với Quý vị về những vấn đề liên quan đến việc Quý vị sử dụng và/hoặc truy cập Trang Web và các dịch vụ trên Trang Web, và bất cứ câu hỏi và/hoặc thắc mắc nào mà Quý vị đưa ra thông qua Trang Web hay bằng cách khác;",
    po_customize:"• Tùy chỉnh trải nghiệm của Quý vị khi sử dụng Trang Web;",
    po_measuring:"• Đánh giá và cải thiện sự trải nghiệm và sự hài lòng của khách hàng;",
    po_publishing:"•  Xuất bản đánh giá của khách hàng, chẳng hạn như Trang web, Đại lý du lịch, Chuyến bay hoặc Khách sạn, ở định dạng kỹ thuật số và / hoặc bản in để truy cập công cộng;",
    po_enforce:"•  Để thực thi các Điều Khoản và Điều Kiện của chúng tôi;",
    po_resolve:"•   Cho các mục đích khác được thông báo cho Quý vị tại thời điểm thu thập.",
    po_purposes:"•  Để giải quyết các tranh chấp hoặc khiếu nại, thu tiền hay các khoản phí, hoặc khắc phục sự cố; và/hoặc",
    po_wemayalso:"Chúng tôi cũng có thể sử dụng Dữ Liệu Cá Nhân của Quý vị và các thông tin khác được thu thập cho mục đích tiếp thị qua Mạng Truyền Thông Mạng Xã Hội bằng cách sử dụng kỹ thuật đồ thị trực tiếp và mở rộng (direct and open graph technology) và cho các mục đích tiếp thị kỹ thuật số và phương thức truyền thống như gửi bưu phẩm trực tiếp đến Quý vị và đăng bài về các sản phẩm mới, các chào bán đặc biệt hoặc các thông tin khác mà chúng tôi cho rằng Quý vị có thể quan tâm. Xin lưu ý rằng Quý vị có thể từ chối bất kỳ tài liệu tiếp thị nào mà chúng tôi gửi cho Quý vị vào bất cứ lúc nào. Hãy làm theo các hướng dẫn hủy bỏ đăng ký được nêu trong tài liệu tiếp thị của chúng tôi nếu Quý vị từ chối bất cứ tài liệu tiếp thị nào và chúng tôi sẽ tôn trọng mong muốn của Quý vị.",
    po_sharing:"3. Chia Sẻ và Chuyển Dữ Liệu Cá Nhân Của Quý vị",
    po_your:"Dữ Liệu Cá Nhân của Quý vị sẽ/có thể được Property Plus tiết lộ cho các công ty liên kết của Property Plus. Tùy từng thời điểm, Property Plus (và/hoặc các công ty liên kết của chúng tôi) cũng có thể tiết lộ Dữ Liệu Cá Nhân của Quý vị với những nhà cung cấp, cung ứng hay đại lý dịch vụ bên thứ ba, cho một hoặc nhiều hơn các mục đích nêu trên. Dịch vụ của bên thứ ba bao gồm nhưng không giới hạn ở dịch vụ máy chủ website, phân tích dữ liệu, tiếp thị, xử lý các giao dịch thẻ tín dụng, và cung cấp dịch vụ.",
    po_please:"Xin lưu ý rằng Property Plus cũng có thể tiết lộ Dữ Liệu Cá Nhân của Quý vị trong các trường hợp sau đây:",
    po_bring:"• Để đưa ra và phản biện chống lại bất kỳ khiếu nại hoặc khiếu kiện nào;",
    po_comply:"•    Để thực hiện lệnh của tòa án, quy trình pháp lý, các yêu cầu hợp pháp, các lệnh hoặc yêu cầu tương đương của các tổ chức thực thi pháp luật hoặc các cơ quan có thẩm quyền;",
    po_investigate:"•   Để điều tra gian lận hoặc sai trái khác theo yêu cầu hoặc cần thiết để tuân thủ bất kỳ luật áp dụng, hoặc để bảo vệ lợi ích hợp pháp của chúng tôi;",
    po_purchasers:"•    Cho người mua liên quan đến bất kỳ việc mua bán, chuyển nhượng, hoặc chuyển giao toàn bộ hoặc một phần công việc kinh doanh hoặc công ty chúng tôi;",
    po_apply:"• Để thực thi hoặc áp dụng các điều khoản và điều kiện áp dụng đối với các sản phẩm và dịch vụ của chúng tôi;",
    po_therights:"• Để bảo vệ các quyền, tài sản hoặc sự an toàn của Property Plus, Người Dùng Trang Web, hoặc bất kỳ người nào khác theo quyết định của Property Plus; và",
    po_situations:"•    Trong bất kỳ tình huống nào khác được pháp luật cho phép.",
    po_consent:"4. Chấp Thuận",
    po_as:"Như đã nêu ở trên, bằng cách truy cập và sử dụng Trang Web, hoặc bằng cách đặt hàng từ Trang Web, hoặc bằng cách đăng ký hay sử dụng các dịch vụ trên Trang Web, hoặc bằng cách nhấn vào nút “Xác Nhận” hoặc cách tương đương khi tạo một tài khoản mới trên Trang Web, Quý vị:",
    po_consentto:"• Chấp thuận cho Property Plus và/hoặc các công ty liên kết của Property Plus thu thập, sử dụng, tiết lộ và/hoặc xử lý Dữ Liệu Cá Nhân của Quý vị được đề cập ở trên cho các mục đích như đã mô tả ở trên.",
    po_withdrawing:"5. Rút Lại Chấp Thuận",
    po_youmay:"Quý vị có thể rút lại sự chấp thuận của Quý vị đối với việc cho chúng tôi thu thập, sử dụng hoặc tiết lộ Dữ Liệu Cá Nhân của Quý vị bất cứ lúc nào, bằng cách gửi cho chúng tôi thông báo hợp lý. Nếu Quý vị muốn rút lại sự chấp thuận của Quý vị, xin vui lòng thông báo cho chúng tôi theo địa chỉ liên hệ được liệt kê dưới đây. Chúng tôi sẽ ngưng thu thập, sử dụng hoặc tiết lộ Dữ Liệu Cá Nhân của Quý vị khi được thông báo, trừ khi luật pháp yêu cầu hoặc nếu chúng tôi có hoạt động kinh doanh hợp pháp hoặc cho các mục đích hợp pháp để duy trì Dữ Liệu Cá Nhân của Quý vị. Lưu ý rằng bằng cách rút sự chấp thuận của Quý vị đối với việc thu thập, sử dụng hoặc tiết lộ Dữ Liệu Cá Nhân của Quý vị, chúng tôi không thể tiếp tục cung cấp cho Quý vị các dịch vụ của chúng tôi và Quý vị đồng ý rằng chúng tôi sẽ không chịu trách nhiệm với Quý vị về bất kỳ tổn thất hoặc thiệt hại nào phát sinh từ hoặc có liên quan đến việc chấm dứt các dịch vụ này.",
    po_cookie:"6. Chính Sách Cookie",
    po_acookie:"Một “cookie” là một tệp nhận diện chữ và số mà chúng tôi chuyển đến ổ đĩa cứng hoặc thẻ nhớ của Quý vị thông qua trình duyệt web khi Quý vị truy cập Trang Web của chúng tôi. Nó cho phép hệ thống của chúng tôi nhận ra Quý vị khi Quý vị truy cập trở lại Trang Web của chúng tôi và cải thiện dịch vụ của chúng tôi cung cấp cho Quý vị. Các thông tin được sử dụng để theo dõi việc sử dụng Trang Web bởi người truy cập và thu thập các báo cáo thống kê về hoạt động Trang Web. Để biết thêm thông tin về cookie xin vui lòng truy cập: www.aboutcookies.org. Cookie cũng có thể được sử dụng để thu thập thông tin tổng hợp về các khu vực mà Trang Web của chúng tôi được truy cập thường xuyên nhất. Thông tin về lưu lượng này có thể được sử dụng để cải thiện nội dung Trang Web của chúng tôi và làm cho việc sử dụng của Quý vị dễ dàng hơn. Nếu Quý vị muốn từ chối cookie của chúng tôi, Quý vị có thể tùy chỉnh cấu hình trình duyệt của Quý vị. Tuy nhiên, một số tính năng Trang Web của chúng tôi có thể không hoạt động nếu Quý vị loại bỏ các tệp cookie khỏi trình duyệt của Quý vị. Nếu Quý vị không cho phép cookie, Quý vị có thể không có khả năng truy cập vào các chức năng hoặc tính năng quan trọng trên Trang Web này và Quý vị chỉ có thể sử dụng Trang Web một cách hạn chế.",
    po_cookies:"Cookie cũng có thể được sử dụng để thu thập thông tin tổng hợp về các khu vực mà Trang Web của chúng tôi được truy cập thường xuyên nhất. Thông tin về lưu lượng này có thể được sử dụng để cải thiện nội dung Trang Web của chúng tôi và làm cho việc sử dụng của Quý vị dễ dàng hơn. Nếu Quý vị muốn từ chối cookie của chúng tôi, Quý vị có thể tùy chỉnh cấu hình trình duyệt của Quý vị. Tuy nhiên, một số tính năng Trang Web của chúng tôi có thể không hoạt động nếu Quý vị loại bỏ các tệp cookie khỏi trình duyệt của Quý vị. Nếu Quý vị không cho phép cookie, Quý vị có thể không có khả năng truy cập vào các chức năng hoặc tính năng quan trọng trên Trang Web này và Quý vị chỉ có thể sử dụng Trang Web một cách hạn chế.",
    po_access:"7. Truy Cập Hoặc Chỉnh Sửa Dữ Liệu Cá Nhân Của Quý vị",
    po_whenyou:"Khi Quý vị cung cấp cho chúng tôi Dữ Liệu Cá Nhân của Quý vị, hãy đảm bảo rằng Dữ Liệu Cá Nhân đó là chính xác và đầy đủ. Nếu Quý vị tin rằng bất kỳ thông tin nào của Quý vị do chúng tôi sở hữu hoặc kiểm soát có sai sót hoặc thiếu sót, xin vui lòng đăng nhập vào tài khoản của Quý vị trên Trang Web và chỉnh sửa thông tin. Ngoài ra, vui lòng cập nhật Dữ Liệu Cá Nhân của Quý vị thông qua tài khoản của Quý vị một cách kịp thời khi có bất kỳ thay đổi nào.",
    po_ifyou:"Nếu Quý vị muốn chỉnh sửa lỗi hoặc thiếu sót trong bất kỳ Dữ Liệu Cá Nhân nào thuộc sở hữu hoặc kiểm soát của chúng tôi mà không thể thực hiện thông qua Trang Web của chúng tôi, hoặc truy cập vào Dữ Liệu Cá Nhân của Quý vị thuộc sở hữu hoặc kiểm soát của chúng tôi, hoặc như được quy định theo pháp luật hiện hành, xin vui lòng gửi yêu cầu của Quý vị đến địa chỉ liên lạc chi tiết của chúng tôi được liệt kê bên dưới. Chúng tôi có thể thu một khoản phí hợp lý cho việc truy cập vào Dữ Liệu Cá Nhân, cho mục đích thu hồi các chi phí phát sinh tương ứng với yêu cầu truy cập.",
    po_toprotect:"Để bảo vệ sự riêng tư và an toàn của Quý vị, chúng tôi sẽ xác minh danh tính của Quý vị trước khi cấp quyền truy cập hoặc thực hiện việc sửa đổi Dữ Liệu Cá Nhân của Quý vị. Chúng tôi sẽ cố gắng đáp ứng các yêu cầu truy cập hoặc chỉnh sửa Dữ Liệu Cá Nhân của Quý vị sớm nhất có thể, trừ khi có ngoại lệ áp dụng.",
    po_personal:"8. Bảo vệ Dữ Liệu Cá Nhân Của Quý vị",
    po_arrangements:"Chúng tôi bảo vệ Dữ Liệu Cá Nhân thuộc sở hữu hoặc kiểm soát của chúng tôi bằng cách duy trì các biện pháp an ninh hợp lý, bao gồm cả các quy trình về vật chất, kỹ thuật và tổ chức, để ngăn chặn việc truy cập, thu thập, sử dụng, tiết lộ, sao chép, sửa đổi, hủy bỏ một cách trái phép hoặc những rủi ro tương tự.",
    po_links:"9. Liên Kết Đến Các Trang Web Khác",
    po_oursite:"Trang Web của chúng tôi có thể chứa các liên kết đến các trang web được quan tâm khác. Tuy nhiên, khi Quý vị đã sử dụng các liên kết này để rời khỏi Trang Web của chúng tôi, Quý vị nên lưu ý rằng chúng tôi không có bất kỳ quyền kiểm soát nào với các trang web khác đó. Xin lưu ý rằng chúng tôi không chịu trách nhiệm về việc thực hiện quyền riêng tư của những trang web đó và khuyến cáo Quý vị nên đọc các quy định về quyền riêng tư của mỗi trang web Quý vị truy cập, mà trang web này có thu thập thông tin cá nhân của Quý vị.",
    po_registration:"10. Đăng Ký và Thành Viên",
    po_allows:"Trang Web này cho phép Quý vị tạo một tài khoản Người Dùng bằng việc đăng ký thành viên, dựa trên các dữ liệu Quý vị cung cấp. Bằng cách cung cấp các dữ liệu, đăng ký và tạo tài khoản, Quý vị phải đảm bảo rằng:",
    po_least:"1.    Quý vị đã bằng hoặc trên 18 tuổi;",
    po_true:"2. Thông tin về Quý vị là đúng và chính xác, hiện thời và đầy đủ theo yêu cầu trong mẫu đăng ký trên Trang Web (“Dữ Liệu Đăng Ký”); và",
    po_update:"3.   Quý vị sẽ cập nhật Dữ Liệu Đăng Ký này để bảo đảm Dữ Liệu Đăng Ký đúng, chính xác và đầy đủ.",
    po_further:"Hơn nữa, Quý vị đồng ý rằng Property Plus không chịu trách nhiệm đối với bất kỳ tổn thất hoặc thiệt hại mà chúng tôi, Quý vị hay bất kỳ bên thứ ba nào phải gánh chịu trong trường hợp sự tổn thất hoặc thiệt hại đó là do thông tin không chính xác hoặc không đầy đủ mà Quý vị cung cấp. Sau khi đăng ký, Quý vị sẽ nhận được một mật khẩu và thông tin nhận dạng Người Dùng (“Tên Đăng Nhập”). Quý vị sẽ chịu trách nhiệm cho việc duy trì tính bảo mật của mật khẩu và Tên Đăng Nhập, và Quý vị hoàn toàn chịu trách nhiệm cho tất cả các hoạt động liên quan đến Tên Đăng Nhập hoặc mật khẩu. Quý vị chỉ có thể sử dụng một Tên Đăng Nhập và mật khẩu tại một thời điểm và không được phép sử dụng nhiều hơn một Tên Đăng Nhập. Mật khẩu của Quý vị bị hạn chế nghiêm ngặt chỉ cho việc sử dụng cá nhân của chính Quý vị, và Quý vị phải đồng ý giữ mật khẩu của Quý vị hoàn toàn bí mật. Quý vị đồng ý thông báo ngay lập tức cho Property Plus về việc sử dụng trái phép mật khẩu hoặc tài khoản của Quý vị hoặc bất kỳ sự vi phạm về an ninh nào. Để bảo mật tốt hơn, hãy đảm bảo rằng Quý vị đăng xuất hoặc thoát khỏi tài khoản của Quý vị sau mỗi lần sử dụng Trang Web này. Quý vị phải đồng ý rằng Property Plus sẽ không chịu trách nhiệm cho bất kỳ tổn thất hoặc thiệt hại nào mà chúng tôi, Quý vị hoặc các bên thứ ba phải gánh chịu phát sinh từ việc Quý vị không tuân thủ các điều khoản này.",
    po_transfer:"11. Chuyển Giao Công Việc Kinh Doanh",
    po_event:"Trong trường hợp có thay đổi về kiểm soát hay thay đổi quyền sở hữu của tất cả hay một phần công việc kinh doanh hoặc công ty của Property Plus, bao gồm cả Trang Web, thì tất cả các Dữ Liệu Cá Nhân của Người Dùng có thể/sẽ là một phần của việc chuyển giao tài sản đó.",
    po_approval:"12. Phê Duyệt Các Thay Đổi Của Chính Sách Quyền Riêng Tư",
    po_provide:"Bằng cách sử dụng Trang Web hoặc các dịch vụ chúng tôi cung cấp, Quý vị đồng ý với việc thu thập, sử dụng, tiết lộ và xử lý các Dữ Liệu Cá Nhân của Quý vị như được quy định trong Chính Sách Quyền Riêng Tư này. Hơn nữa, nếu Quý vị sử dụng dịch vụ của chúng tôi, chúng tôi bảo lưu quyền thu thập, sử dụng, tiết lộ và xử lý Dữ Liệu Cá Nhân của Quý vị theo Chính Sách Quyền Riêng Tư này. Tùy từng thời điểm, Property Plus có thể thay đổi Chính Sách Quyền Riêng Tư này. Như đã mô tả trong phần đầu của Chính Sách Quyền Riêng Tư này, chúng tôi sẽ hiển thị những thay đổi như vậy trên Trang Web này để thông báo cho Quý vị.",
    po_precedence:"13. Thứ Tự Ưu Tiên",
    po_inconsistency:"Nếu Quý vị đã đồng ý với Điều Khoản Trang Web của chúng tôi, trong trường hợp có sự không thống nhất giữa các Điều Khoản Trang Web và Chính Sách Quyền Riêng Tư này, Điều Khoản Trang Web sẽ được ưu tiên áp dụng.",
    po_contactus:"14. Liên Hệ Với Chúng Tôi",
    po_questions:"Nếu Quý vị có bất kỳ câu hỏi hoặc yêu cầu liên quan đến Chính Sách Quyền Riêng Tư, xin vui lòng liên hệ Nhân viên Bảo vệ Dữ liệu của chúng tôi theo chi tiết sau đây: support@propertyplus.com.vn, hoặc nhân viên được Property Plus chỉ định bằng cách thông báo cho Quý vị thông qua các hình thức thư từ, hóa đơn, email hoặc Trang Web.Các quy định về Chính Sách Quyền Riêng Tư này được dịch từ phiên bản gốc tiếng Anh, và được cung cấp nhằm tạo sự thuận tiện cho việc xem xét của bạn. Có thể có một số khác biệt giữa bản dịch và bản gốc tiếng Anh, và trong trường hợp có bất kỳ sự khác biệt nào như vậy, thì sự khác biệt đó được coi là lỗi dịch thuật và bản tiếng Anh sẽ được ưu tiên áp dụng. Nếu nghi ngờ về tính chính xác của thông tin chứa trong bản dịch, xin vui lòng tham khảo phiên bản tiếng Anh.",
    po_date:"Ngày hiệu lực: Tháng 01 năm 2019.",

    placeholder_search_home:"Nhập vị trí hoặc từ khóa dự án",

}

var translationsEN = {
    placeholder_search_home:"Type Location or Project Keyword",

    search_bar_livingHaNoi: "Easy living in HaNoi",
    search_bar_price: "Price",
    search_bar_room: "Room",
    search_bar_area: "Area",
    search_bar_facilities: "Facilities",
    menu_support:"Support",
    menu_blog: "Blog",
    menu_about_us: "Our story",
    menu_customer: "Support",
    menu_signup: "Sign up",
    menu_help: "Help",
    menu_login: "Login",
    menu_visit: "Your visit list",
    menu_host: "Become a host",
    btn_register: "Signup",
    blog_news:"News",
    blog_experience:"Experience",
    blog_tips:"Tips",
    blog_keyword:"Keyword",
    blog_search:"Search",
    blog_readmore:"READ MORE",
    blog_loadmore:"Load more",
    host_save:"Save",
    host_chooseyourapartment:"Choose your apartment",
    host_tenant:"tenant",
    host_overview:"Overview",
    host_problem:"Problem",
    host_describe:"Describe",
    host_information:"Information",
    host_photos:"Photos",
    host_location:"Location",
    host_time:"Time",
    host_billingdetail:"Billing Detail",
    host_property:"Property",
    host_article:"Article",
    host_datebilled:"Date Billed",
    host_amountbilled:"Amount Billed",
    host_paymentstatus:"Payment Status",
    host_detailcase:"Detail Case",
    host_calendar:"Calendar",
    host_downloadcontract:"Download Contract",
    host_name:"Name",
    host_type:"Type",
    host_project:"Project",
    host_nobedroom:"No.Bedroom",
    host_nobathroom:"No.Bathroom",
    host_area:"Area",
    host_address:"Address",
    host_enteralocation:"Enter a location",
    host_addbannerimage:"Add banner image",
    host_addanother:"Add another",
    host_thumbnail:"Thumbnail photo",
    host_banner:"banner photo",
    host_dragthepintoadjustitslocation:"Drag the pin to adjust its location",
    project_featureproject:"FEATURE PROJECT",
    project_onairproject:"ON-AIR PROJECT",
    project_explore:"Explore",
    project_seelist:"See list",
    project_upcomingproject:"UP-COMING PROJECT",

    price_range:"Price Range",
    clear:"Clear",
    rooms:"Rooms",
    bedrooms:"Bedrooms",
    bathrooms:"Bathrooms",
    area:"Area",
    facilities:"Facilities",
    introducing_property_plus:"Introducing Property Plus",
    explore_our_story:"Explore our story",
    see_how_our_service_is_best:"See how our service is best",
    standard_quality:"Standard Quality",
    fast_service:"Fast service",
    call_center:"24/7 call center",
    multi_language_support:"Multi-language support",
    explore_all_service:"Explore all service",
    choose_your_new_home:"Choose your new home",
    estimate_price:"Estimate Price",
    see_more:"See more",
    project_have_our_service:"Our projects",
    explore_all:"Explore all",
    show_map:"Show map",
    view_category:"VIEW",
    apartment_uppercase:"Apartment",
    night_text:"night",
    share_text:"Share",
    bookmark_text:"Favourite",
    about_this_listing:"ABOUT THIS LISTING",
    tour_this_home:"TOUR THIS HOME",
    living_room:"Living room",
    other_text:"Other",
    amenities:"AMENITIES",
    owner:"Owner",
    join_in:"Join in",
    estimate_price_included_service:"Estimate price included service",
    per_text:"per",
    apartment_price:"Apartment price",
    month_text:"month",
    service_total_price:"Service total price",
    service_package:"Service package",
    custom:"Custom",
    basic:"Basic",
    management_fee_by:"Management fee by PP",
    foreign_tv:"Foreign TV",
    laundry_cleaning:"Laundry & Cleaning",
    drinking_water:"Drinking water",
    detergent:"Detergent",
    toilet_paper:"toilet paper",
    electric_water_bill:"Electric & water bill",
    include_tax:"Include tax",
    send_visiting_request:"SEND VISITING REQUEST",
    similiar_listing:"SIMILAR LISTING",
    bookmark_uppercase:"Favourite",
    dashboard:"Dashboard",
    manage:"Manage",
    listing:"Listing",
    help:"Help",
    edit_profile:"Edit profile",
    account_setting:"Account setting",
    logout:"Log out",
    provide_information:"Provide information",
    upload_picture:"Upload picture",
    set_price:"Set price",
    verify:"Verify",
    congratulation_finish:"Congratulation, your apartment uploading is finish. It will be appear soon.",
    home:"Home",
    create_new:"Create new",
    row_1_step_1_1:"Let's get start listing your apartment",
    row_2_step_1_1:"What kind of place do you have?",    
    row_3_step_1_1:"Name your apartment's project",
    continue:"Continue",
    row_1_step_1_2:"Let's us know more about your apartment",
    row_2_step_1_2:"How many total bedroom your property have?",
    row_3_step_1_2:"How many total bathrooms your property have?",
    row_4_step_1_2:"How much area of your house",
    area_required:"Area is required",
    address_required:"Address is required",
    phone:"Phone",
    phone_required:"Phone is required",
    row_5_step_1_2:"Name your apartment ( Optional )",
    row_6_step_1_2:"Describe about your apartment ( Optional )",
    next:"Next",
    cancel:"Cancel",
    back:"Back",
    row_1_step_1_3:"Is the pin in  the right place?",
    row_2_step_1_3:"If needed, you can drag the pin to adjust its location.",
    add_banner_image:"Add banner image",
    great_progress:"Great progress",
    row_1_step_2_1:"Now let's get some details about your apartment then you can ready to publish your listing.",
    row_2_step_2_1:"Tips : Apartment have reality image help rentel make decision faster.",   
    add_another:"add another", 
    row_1_step_3_1:"Set up  price for your apartment",
    row_2_step_3_1:"Apartment management fee",
    row_3_step_3_1:"Similiar listing",
    row_1_step_3_2:"Choose your facilities",
    row_1_step_4_1:"To have a legal basis for doing business on PROPERTYPLUS, please post a photo or a scanned copy of the certificate of ownership of the land or a letter of authorization to use the property.",
    row_2_step_4_1:"- The upload size does not exceed 5MB.",
    row_3_step_4_1:"- The number of images per download does not exceed 5.",
    row_4_step_4_1:"Drag n drop or click to upload ",
    finish:"Finish",
    all:"All",
    listed:"Listed",
    description:"Description",
    listing_on_project:"LISTING ON PROJECT",
    general:"General",
    host_text:"Host",
    public_infomation:"Public infomation",
    full_name:"Full name",
    profile_photo:"Profile photo",
    row_1_edit_profile:"Clear frontal face photos are an important way for hosts and guests to learn about each other. Be sure to use a photo that clearly shows your face and doesn’t include any personal or sensitive info you’d rather not have landlord or tenant see.",
    upload_ava_text:"Upload a file from your device",
    private_infomation:"Private infomation",
    row_2_edit_profile:"We won't never share your private information with another Property Plus users.",
    i_am:"I am",
    birth_date:"Birth date",
    email:"Email",
    phone_number:"Phone number",
    verification:"Verification",
    row_3_edit_profile:"You'll need to provide indentification when you make a renting contract, so get a head by start by doing it now.",
    upload:"Upload",
    option_infomation:"Option infomation",
    company:"Company",
    company_address:"Company Address",
    row_4_edit_profile:"Give our Customer Service team a trusted contact we can alert in an urgent situation.",
    describe_yourself:"Describe Yourself",
    your_visiting_list:"Your visiting list",
    your_apartment:"Your apartment",
    visting_schedule:"Visiting schedule",
    visting_history:"Visiting history",
    you_visited:"You visited",
    apartment:"apartment",
    billing:"Billing",
    send_issue:"Send issue",
    your_using_service:"Your using service",
    service:"Service",
    quantity:"Quantity",
    maintance_management:"Maintance & management",
    default:"default",
    cable_tv:"Cable TV",
    times:"times",
    week:"week",
    bottles:"bottles",
    change:"Change",
    current_balance:"Current Balance",
    electricity_charge:"Electricity charge",
    not_paid:"Not paid",
    paid:"Paid",
    hot_water_charge:"Hot water charge",
    cold_water_charge:"Cold water charge",
    report_a_problem:"Report a problem",
    support_inbox:"Support Inbox",
    reported_billing_issue:"You reported a billing issue",
    last_update:"Last update",
    sending:"SENDING",
    solved:"SOLVED",
    in_progress:"IN PROGRESS",
    we_sent_you_a_message:"We sent you a message",
    rate_your_experience:"Rate your experience",
    change_your_password:"Change your password",
    old_password:"Old password",
    new_password:"New password",
    confirm_new_password:"Confirm new password",
    passwords_not_match:"Passwords does not match",
    update_password:"Update Password",
    refer:"Refer",
    pending:"Pending",
    approved:"Approved",
    signupFB:"Sign up with Facebook",
    signupGG:"Sign up with Google",
    signupEmail:"Sign up with Email",
    or:"or",
    signEmail:"Sign up with Email",
    haveAccount:"Already have an account",
    login:"Login",
    loginFB:"Log in with Facebook",
    loginGG:"Log in with Google",
    forgotPW:"Forgot password",
    dhaveAccount:"Don't have an account",
    signup:"Sign up",
    signupwith:"Sign up with",
    bysignin:"By sign up, I agree to PropertyPlus's ",
    termofservice:"Term of service ,",
    privacys:"Privacy policy ,",
    and:"and",
    copyright:"Copyright policy",

    career:"Career",
    policy:"Policy",
    why_host:"Why host",
    hosting:"Hosting",
    community:"Community center",
    terms:"Terms",
    privacy:"Privacy",
    site_map:"Site Map",

    technology:"TECHNOLOGY",
    besides:"Besides, PropertyPlus always makes all endeavor to delight our Customers (both tenants and Landlords), by applying a wide range of peer-to-peer information systems for total control.",
    From:"We use virtual reality technology, Matterport, which provide the most factual and precise imagination so you can visit the apartment without going directly. And we guarantee, what you see is true.",
    canbe:"Till 2020, Property Plus orients to build up a synchronized system of electronic contracts, management and customized services. House-keeping and technique-maintenance procedures will be monitored through automated mobile application. They helps reduce waiting times when problems arise.",
    screen:"From searching apartments, signing contracts to monitoring your apartments, you can be away from Hanoi half way round the world and do it all over the computer screen.",
    
    sv_house:"House Keeping Department",
    sv_5star:"5-Star Standard Services",
    sv_beinghonest:"Being honest, experienced and qualified staffs who have been trained and worked in the most professional environment, House Keeping Deparment of Property Plus is self-confident to sastify the most demanding Customers.",
    sv_procedure:"PROCEDURE",
    sv_standard:"Standard procedure is designed and trained by experienced experts from reputable international 5-star hotels",
    sv_trust:"TRUST",
    sv_withour:"With our honest and friendly personnel, Customers always feel safe when they are away from home.",
    sv_experience:"EXPERIENCE",
    sv_beingable:"Being able to solve relevant issues in the fastest and most professional way.",
    sv_tool:"TOOL",
    sv_tools:"Tools, chemicals are controlled strictly to ensure quality of services and safety for human, property and environment.",
    sv_technique:"Technique- Maintenance Department",
    sv_beingalways:"Being always for Customers",
    sv_devoting:"Devoting all time is priority and slogan of Property Plus maintance technicians. Our employees are always available to assist and help Customers solve obstacles arising in Customers’ life",
    sv_speed:"SPEED",
    sv_presenting:"Presenting at site to inspect incidents within 120 minutes right upon",
    sv_reception:"reception of information from Customers",
    sv_responsibility:"RESPONSIBILITY",
    sv_beingableto:"Being able to solve relevant issues in the fastest and most ",
    sv_professionalway:"professional way.",
    sv_management:"Management Department",
    sv_resolution:"Professional resolution",
    sv_through:"Through an only one hotline, all problems of Customers shall be conveyed to all relevant departments.",
    sv_communication:"COMMUNICATION",
    sv_three:"Three language in communication: English, Japanese and Vietnamese",
    sv_availability:"AVAILABILTY",
    sv_availableto:"Being always available to receive feedback from Customers 24/7",
    sv_attitude:"ATTITUDE",
    sv_working:"Working from heart, listening actively, welcoming and embracing all claims and feedback from Customers in any cases",
    

    ab_general:"General",
    ab_organization:"Organization structure",
    ab_company:"Company Model",
    ab_history:"HISTORY AND DEVELOPMENT",
    ab_vision:"VISION AND MISSION",
    ab_core:"CORE VALUES",
    ab_development:"DEVELOPMENT ORIENTATION",
    ab_taking:"Taking part in market of housing since 2011, Dai Loi is always concerned that value and economic potential of luxury real estate in Vietnam have not been promoted as much as they should be. Realizing the shortage of professional apartment services provided to foreigners in Vietnam, Dai Loi forcefully develop the trademark PROPERTY PLUS with 5-star standard services, therefrom we satisfy daily life demand for foreigners. With competence of caring and managing apartments, PROPERTY PLUS can solve Customers’ difficulties and obstacles in accessing to luxurious apartments owned by Vietnamese individual owners. With a team of experienced, hospitable and professionally trained employees- technicians, our mission is to create a professional yet comfortable life for Customers, in which they are not concerned about problems arising in daily life. Having experience of managing house for hundreds of Customers from different nationalities, combining with technology development, PROPERTY PLUS tends to optimize the market of housing real estate for both Landlords and Customers.Thereby, Landlords can lease their luxurious real estate at any time at desirable price.Lessees can easily rent luxurious serviced apartments at any time at attractive price",
    ab_vis:"VISION :",
    ab_market:"Desiring to make Customers bewitched by services supplied by Vietnamese people for its pioneering, PROPERTY PLUS orients to be one of leading companies in the market of real estate for foreigners in Vietnam with International-level services.",
    ab_mission:"MISSION :",
    ab_concerned:"We help house owners and foreign lessees feel safe to enjoy their life, not concerned about daily problems of housing. ",
    ab_cor:"CORE VALUES",
    ab_isalways:"Foundation of PROPERTY PLUS is built on our firm relationship with Investors, Partners, Customers, Employees and the whole society, Property Plus is aware that all the said factors are the most precious things one company has. PROPERTY PLUS is always committed to remain values to stabilize and consolidate the relationship.",
    ab_creativity:"1. CREATIVITY : Constant innovation, promotion and development. Spirit of dare to think and dare to do.",
    ab_commit:"2. COMMIT : Making all best endeavors to ensure commitments with proper and higher quality.",
    ab_orientation:"3. ORIENTATION : Desire for pioneering and creating new trends.",
    ab_conscientious:"4. CONSCIENTIOUS : Caring Customers with excitement and voluntary spirit.",
    ab_cooperation:"5. COOPERATION : Respecting all relationship with Customers, Partners, Counterparts, Investors and the whole Society.",
    ab_minh:"With current favorable conditions and development orientation, PROPERTY PLUS aims at being the biggest name in Vietnam in the coming 5 years with respect to connecting house owners with long-term lessees, PROPERTY PLUS also expects to increase number of apartments to 5000, accounting for 5% total luxurious apartments in Vietnam, to present in the biggest cities of Vietnam like Ha Noi, Ho Chi Minh, Đa Nang, Hai Phong, Nha Trang and others.",
    abu_business:"BUSINESS MODEL",
    abu_tenants:"INTERESTS OF TENANTS",
    abu_landlord:"INTERESTS OF LANDLORDS",
    abu_friendly:"Property Plus orients to build an integrated model which is both complex and user-friendly to each beneficiary of our community.",
    abu_butle:"Dedicated Butler",
    abu_large:"• Large and beautiful apartments with attractive prices.",
    abu_reception:"• Professional reception and management",
    abu_good:"• Good location and best facilities such as gym, swimming pool, etc.",
    abu_star:"• 5-star standard house-keeping services",
    abu_periodic:"• Periodic technical maintenance under Property Plus’ standard of input control",
    abu_procedural:"• Procedural support: online leasing contract, tax payment, paying bills, etc.",
    abu_security:"• High security: QR code to access the apartment, fire safety, safety of social issues.",
    abu_discover:"• Opportunity to discover and integrate into local culture and life.",
    abu_house:"Professional House Manager",
    abu_pp:"PP owns a team of highly qualified and experienced real estate brokers in Vietnam that will help your apartment reach out to potential tenants in the shortest possible time. Then Property Plus will manage all aspects of the leasing: contracts, management, finance, and maintenance.",
    abu_dedicated:"• Dedicated and knowledgeable consultants with 24/7 customer support.",
    abu_marketing:"• Marketing and Searching for tenants on multiple channels.",
    abu_optimizing:"• Optimizing empty days of an apartment by short-term rental service.",
    abu_procedural:"• Procedural support: online leasing contract, tax payment, paying bills, etc.",
    abu_standard:"• 5-star standard house-keeping services",
    abu_periodic:"• Periodic technical maintenance under Property Plus’ standard of input control.",
    abu_free:"• Free allowance of 3 million VND/year for technical maintenance.",
    abu_security:"• High security: using QR code and apartment monitoring software.",
    abu_parties:"• Information transparency in all procedures between the parties.",
    ab_team:"OUR TEAM",
    ab_ceo:"CEO & Founder",
    ab_staff:"EXCELLENT STAFF",

    our_technology:"Our technology",
    apartment_searching_platform:"Apartment searching platform",
    mutil_party_communication_system:"Multi-party communication system",
    service_and_management_system:"Service and management system",
    customer_realationship_management_system:"Customer relationship management system",
    explore_our_tech:"Explore our tech",  

    content_about_us:"<p>In Property Plus, we deeply believe that relocating to a foreign country should not be a daunting experience but great and memorable experiences. Property Plus, as the smart solution of living, we always do our best to bring greatest experiences for international friends. </p>"+
                    "<p>Joining with Property Plus, you will be immersed in the feeling of luxurious and flexible living style; and the feeling of being welcomed, right from the moment you step through the doors. You will relish a customized living experience with wide range of high standard service and an authentic atmosphere. You will enjoy a perfectly-balanced life between business and pleasure.With Property Plus, you will be at home anywhere.</p>",

    po_policy:"PRIVACY POLICY",
    po_propertyplus:"Propertyplus.com.vn is owned and operated by Dai Loi Trade and Consultancy of Real Estate Co. Ltd (“Property Plus”, “Us”, “We”, or “Our”). This Privacy Policy describes how we collect, use, disclose, process and protect personally identifiable information (“Personal Data”) that you (the “User”) may provide in connection with Property Plus’s services available through the website located at www.propertyplus.com.vn. Personal Data means data, whether true or not, about an individual.References to the Site are deemed to include derivatives thereof, including but not necessarily limited to mobile websites and applications. By visiting or using the Site, you agree and consent to the collection, use, disclosure and processing of your Personal Data in accordance with this Privacy Policy and/or the Website Terms. If you do not agree to the Privacy Policy below, please leave the Site immediately.",
    po_fromtime:"From time to time, Property Plus may revise this Privacy Policy to reflect changes in the law, our Personal Data collection and use practices, the features of our Site, or advances in technology. If we make revisions that change the way we collect or use your Personal Data, those changes will be posted in this Privacy Policy and the effective date will be noted at the beginning of this Privacy Policy. Therefore, you should review this Privacy Policy periodically so that you are up to date on our most current policies and practices. Property Plus will also prominently post such material changes prior to implementing the change. If you do not agree with any changes or modifications to the Privacy Policy, please do not continue using the Site. You will be deemed to have consented to any modification of the Privacy Policy when you use the Site after the effective date of the modification.",
    po_collect:"1. Information We Collect",
    po_we:"We collect the Personal Data that you provide to us when using the Site. This includes but is not limited to: your name, Property Plus user identification and login credentials, address, phone number, email address, hotel name, hotel location, and/or length of stay. We also collect non-personally identifiable information including but not limited to your internet protocol (IP) address, geographic location, operating system type, nationality, search preferences, as well as other generic Internet usage related data.",
    po_howwe:"2. How We Use Your Information",
    po_wemay:"We may use your Personal Data and other information gathered through the Site for the following purposes:",
    po_registering:"•   Registering, managing and/or administering your use and/or access of the Site;",
    po_managing:"•  Managing, operating, administering and providing you the services offered on the Site;",
    po_contacting:"•    Contacting you on matters relating to your use and/or access of the Site and services on the Site, and any enquiries and/or requests submitted by you through the Site or otherwise;",
    po_customize:"• To customize your experience when using the Site;",
    po_measuring:"• Measuring and improving customer experience and satisfaction;",
    po_publishing:"•    Publishing customer reviews, such as of the Site, Travel Agents, Flights or Hotels, in digital and/or print format for public access;",
    po_enforce:"•   To enforce our Terms and Conditions;",
    po_resolve:"•   To resolve disputes or complaints, collect payment or fees, troubleshoot problems; and/or",
    po_purposes:"•  For the purposes otherwise that will be made available to you at the point of collection.",
    po_wemayalso:"We may also use your Personal Data and other information collected for Social Media marketing using direct and open graph techniques; for digital and conventional marketing purposes such as sending you direct mailers about new products, and special offers or other information which we think you may find interesting. Please note that you may opt out of any marketing materials we may send to you at any time. Please follow the unsubscribe instructions set out in our marketing materials if you choose to opt out of any marketing materials and we will respect your wishes.",
    po_sharing:"3. Sharing and Transferring Your Personal Data",
    po_your:"Your Personal Data may be shared by Property Plus to our affiliate companies. Property Plus (and/or its affiliate companies) may also disclose your Personal Data to third party service providers, suppliers or agents for one or more of the above purposes. Third party services include but are not limited to: website hosting, data analysis, marketing, processing credit card transactions, and service provisions.",
    po_please:"Please note that Property Plus may disclose your Personal Data in the following situations:",
    po_bring:"• To bring or defend against any claims or suits;",
    po_comply:"•    To comply with court orders, judicial processes, legitimate requests, warrants or equivalent by law enforcement officials or the authorities;",
    po_investigate:"•   To investigate fraud or other wrongdoing or as otherwise required or necessary in order to comply with any applicable law, or to protect our legitimate interests;",
    po_purchasers:"•    To the purchasers in connection with any sale, assignment, or other transfer of all or part of our business or company;",
    po_apply:"• To enforce or apply the terms and conditions applicable to our products and services;",
    po_therights:"• To protect the rights, property or safety of Property Plus, other Site Users, or any other person according to Property Plus’s discretion; and",
    po_situations:"•    For any other situations which is allowed under law.",
    po_consent:"4. Consent",
    po_as:"As stated above, by browsing and using the Site, ordering a product from the Site, registering for or using any service on the Site, or by clicking the “Confirm” button or equivalent when you create a new account on the Site, you:",
    po_consentto:"•   Consent to Property Plus and/or Property Plus’s affiliate companies collecting, using, disclosing and/or processing your above mentioned personal data for the purposes as described above.",
    po_withdrawing:"5. Withdrawing Consent",
    po_youmay:"You may withdraw your consent to our collection, use or disclosure of your personal data at any time, by giving us reasonable notice. If you wish to withdraw your consent, please inform us at our contact details listed below. We will cease to collect, use or disclose your personal data upon notification, unless required by law or if we have legitimate business or legal purposes for retaining it. Note that by withdrawing your consent to our collection, use or disclosure of your personal data, we may not be able to continue providing you with our services and you agree that we will not be liable to you for any losses or damages arising out of or in relation to such termination of services.",
    po_cookie:"6. Cookie Policy",
    po_acookie:"A “cookie” is an alphanumeric identifier which we transfer to your hard drive or memory card through your web browser when you visit our Site. It enables our own system to recognise you when you visit our Site again and improve our service to you. The information is used to track visitor use of the Site and to compile statistical reports on Site activity. For further information about cookies visit www.aboutcookies.org",
    po_cookies:"Cookies may also be used to compile aggregate information about areas of our Site that are visited most frequently. This traffic information can be used to enhance the content of our Site and make your use of it easier. If you wish to reject our cookie, you can configure your browser to do so. However, some of our Site features may not function if you remove cookies from your browser. If you do not enable cookies, you may only be able to use the Site on a limited basis.",
    po_access:"7. Access to or Correction of Your Personal Data",
    po_whenyou:"When you provide us with your Personal Data, please ensure that it is accurate and complete. If you believe that any of your information under our possession contains errors or omissions, please log into your account on the Site and correct the information. In addition, please update your Personal Data through your account in a timely manner, should there be any changes.",
    po_ifyou:"If you wish to correct an error or omission in any Personal Data under our possession that cannot be corrected via our Site, or to access your Personal Data under our possession or control, or as provided for by applicable laws, please submit your request to our contact details listed below. We may charge you a reasonable fee for access to the Personal Data, for the purpose of recovering the incremental costs of responding to the access request.",
    po_toprotect:"To protect your privacy and security, we will verify your identity before granting access or making changes to your Personal Data. We will endeavor to answer requests for access or correction to your Personal Data as soon as reasonably possible, unless an exception applies.",
    po_personal:"8. Protecting Your Personal Data",
    po_arrangements:"We protect Personal Data by maintaining reasonable security arrangements, including physical, technical and organizational procedures, to prevent unauthorised access, collection, use, disclosure, copying, modification, disposal or similar risks.",
    po_links:"9. Links to Other Websites",
    po_oursite:"Our Site may contain links to other websites of interest. However, once you have used these links to leave our Site, you should note that we do not have any control over that other website. Please note that we are not responsible for the privacy practices of such other websites and advise you to read the privacy statements of each website you visit which collects personal information.",
    po_registration:"10. Registration and Memberships",
    po_allows:"This Site allows you to create a user account with the membership register, based on the data you provide. By providing the data, registering, and creating your account, you warrant that:",
    po_least:"1.    You are at least 18 years of age;",
    po_true:"2. Information about you is true and accurate, current and complete as required in the registration form on the Site (the “Registration Data”); and",
    po_update:"3.   You will update this Registration Data to keep it true, accurate and complete.",
    po_further:"Further, you agree that Property Plus is not responsible for any loss or damages that may be suffered by us, you or any third parties, where such loss or damage is caused by inaccurate or incomplete information given by you. After registering, you will receive a password and user identification (“Username”). You are responsible for maintaining the confidentiality of the password and Username, and you are fully responsible for all activities related to the Username or password. You can only use a single Username and password at one time and are not allowed to use more than one Username. Your password is strictly for your own personal use only, and you agree to keep your password strictly confidential. You agree to immediately notify Property Plus about unauthorized use of your password or account or any other breach of security. For greater security, please ensure that you logout or exit from your account after each use of this Site. You agree that Property Plus will not be liable for any loss or damage suffered by us, you or third parties arising from your failure to comply with this clause.",
    po_transfer:"11. Transfer of Business",
    po_event:"In the event of a change of control or change of ownership of all or part of the Property Plus business or company, including the Site, then all Users’ Personal Data may/will be part of the transfer of such assets.",
    po_approval:"12. Approval of Privacy Policy Changes",
    po_provide:"By using the Site or the services we provide, you agree to the collection, use, disclosure and processing of your Personal Data as set forth in this Privacy Policy. Furthermore, if you use our services, we reserve the right to collect, use, disclose and process your Personal Data in accordance to this Privacy Policy. From time to time, Property Plus may change this Privacy Policy. We will display the changes on this Site prior to making the changes.",
    po_precedence:"13. Order of Precedence",
    po_inconsistency:"If you have agreed to our Website Terms, in the event of inconsistency between such Website Terms and this Privacy Policy, Website Terms shall prevail.",
    po_contactus:"14. Contact Us",
    po_questions:"If you have any questions or requests relating to this Privacy Policy, please contact our Data Protection Officer at the following details, or such person as Property Plus may designate by informing you through any letter, invoice, email or the Site: support@propertyplus.com.vn",
    po_date:"Effective date: 01/01/2019 ",
}

var translationsJP = {
    placeholder_search_home:"プロジェクトの場所またはキーワードを入力してください",

    menu_about_us:"私たちの物語",
    refer:"参照する",
    menu_customer: "サポート",
    menu_signup: "サインアップ",
    menu_support:"サポート",
    menu_blog: "ブログ",
    menu_help: "助けて",
    menu_login: "ログイン",
    menu_visit: "あなたの訪問リスト",
    menu_host: "ホストになる",

    btn_register: "サインアップ",
    blog_news:"ニュース",
    blog_experience:"経験",
    blog_tips:"ヒント",
    blog_keyword:"キーワード",
    blog_search:"サーチ",
    blog_readmore:"続きを読む",
    blog_loadmore:"もっと読み込む",
    host_save:"保存する",
    host_chooseyourapartment:"あなたのアパートを選択する",
    host_tenant:"テナント",
    host_overview:"概要",
    host_problem:"問題",
    host_describe:"説明する",
    host_information:"情報",
    host_photos:"写真",
    host_location:"ロケーション",
    host_time:"時間",
    host_billingdetail:"請求の詳細",
    host_property:"プロパティ",
    host_article:"記事",
    host_datebilled:"請求書日付",
    host_amountbilled:"請求額",
    host_paymentstatus:"支払い状況",
    host_detailcase:"詳細ケース",
    host_calendar:"カレンダー",
    host_downloadcontract:"契約をダウンロードする",
    host_name:"名",
    host_type:"タイプ",
    host_project:"プロジェクト",
    host_nobedroom:"ベッドルームの数",
    host_nobathroom:"バスルームの数",
    host_area:"エリア",
    host_address:"住所",
    host_enteralocation:"場所を入力してください",
    host_addbannerimage:"バナー画像を追加する",
    host_addanother:"別のものを追加する",
    host_thumbnail:"サムネイル写真",
    host_banner:"バナー写真",
    host_dragthepintoadjustitslocation:"ピンをドラッグして位置を調整する",
    project_featureproject:"フィーチャープロジェクト",
    project_onairproject:"オンエアプロジェクト",
    project_explore:"探検する",
    project_seelist:"リストを見る",
    project_upcomingproject:"アップ・アップ・プロジェクト",

    price_range:"価格帯",
    clear:"クリア",
    rooms:"部屋",
    bedrooms:"ベッドルーム",
    bathrooms:"バスルーム",
    area:"エリア",
    facilities:"施設",
    introducing_property_plus:"導入 Property Plus",
    explore_our_story:"私たちの物語を探る",
    see_how_our_service_is_best:"私たちのサービスがどのように最高のものかを見て",
    standard_quality:"標準品質",
    fast_service:"迅速なサービス",
    call_center:"24/7 コールセンター",
    multi_language_support:"多言語サポート",
    explore_all_service:"すべてのサービスを探索する",
    choose_your_new_home:"あなたの新しい家を選んでください",
    estimate_price:"見積価格",
    see_more:"続きを見る",
    project_have_our_service:"プロジェクトは私たちのサービスを持っている",
    explore_all:"すべてを見る",
    show_map:"地図を表示",
    view_category:"VIEW",
    apartment_uppercase:"アパート",
    night_text:"夜",
    share_text:"シェア",
    bookmark_text:"ブックマーク",
    about_this_listing:"このリストについて",
    tour_this_home:"このホームへ",
    living_room:"リビングルーム",
    other_text:"その他",
    amenities:"アメニティ",
    owner:"オーナー",
    join_in:"参加する",
    estimate_price_included_service:"見積価格に含まれるサービス",
    per_text:"〜ごと",
    apartment_price:"アパート価格",
    month_text:"月",
    service_total_price:"サービス合計金額",
    service_package:"サービスパッケージ",
    custom:"カスタム",
    basic:"ベーシック",
    management_fee_by:"PPによる管理手数料",
    foreign_tv:"外国のテレビ",
    laundry_cleaning:"ランドリー＆クリーニング",
    drinking_water:"水を飲んでいる",
    detergent:"洗剤",
    toilet_paper:"トイレットペーパー",
    electric_water_bill:"電気および水道料金",
    include_tax:"税金を含む",
    send_visiting_request:"訪問要請を送信する",
    similiar_listing:"同様のリスト",
    bookmark_uppercase:"ブックマーク",
    dashboard:"ガバナンス",
    manage:"管理",
    listing:"リスト",
    help:"助けて",
    edit_profile:"プロファイル編集",
    account_setting:"アカウントの設定",
    logout:"ログアウト",
    provide_information:"情報を提供する",
    upload_picture:"写真をアップロードする",
    set_price:"セット価格",
    verify:"確認",
    congratulation_finish:"おめでとう、アパートのアップロードは終了です。 すぐに表示されます。",
    home:"ホーム",
    create_new:"新しく作る",
    row_1_step_1_1:"あなたのアパートをリストアップしよう",
    row_2_step_1_1:"どのような場所がありますか？",    
    row_3_step_1_1:"アパートのプロジェクトに名前をつける",
    continue:"Continue",
    row_1_step_1_2:"あなたのアパートについてもっと知りましょう",
    row_2_step_1_2:"あなたの財産はどれくらいの合計寝室ですか？",
    row_3_step_1_2:"あなたの物件にはどれくらいの浴室がありますか？",
    row_4_step_1_2:"あなたの家のどのくらいの面積",
    area_required:"エリアが必要です",
    address_required:"アドレスは必須です",
    phone:"電話番号",
    phone_required:"電話番号は必須です",
    row_5_step_1_2:"あなたのアパートに名前を付けてください（オプション）",
    row_6_step_1_2:"アパートについての説明（オプション）",
    next:"次",
    cancel:"キャンセル",
    back:"バック",
    row_1_step_1_3:"ピンは正しい場所にありますか？",
    row_2_step_1_3:"必要に応じて、ピンをドラッグしてピンの位置を調整することができます。",
    add_banner_image:"バナー画像を追加する",
    great_progress:"大きな進歩",
    row_1_step_2_1:"次に、あなたのアパートについていくつかの詳細を聞いてみましょう。あなたはあなたのリストを公開する準備ができています。",
    row_2_step_2_1:"ヒント：アパートは現実のイメージを持っているので、レンタルは意思決定を速くします。",   
    add_another:"別のものを追加する", 
    row_1_step_3_1:"あなたのアパートの価格を設定する",
    row_2_step_3_1:"アパート管理手数料",
    row_3_step_3_1:"同様のリスト",
    row_1_step_3_2:"あなたの施設を選択してください",
    row_1_step_4_1:"PROPERTYPLUSでビジネスを行うための法的基盤を持つには、その土地の所有権証明書または使用許諾書の写真またはスキャンした写しを投稿してください。",
    row_2_step_4_1:"- アップロードサイズは5MBを超えません。",
    row_3_step_4_1:"- ダウンロードあたりの画像数は5を超えません。",
    row_4_step_4_1:"ドラッグアンドドロップ、またはクリックしてアップロード ",
    finish:"フィニッシュ",
    all:"すべて",
    listed:"リストされた",
    description:"説明",
    listing_on_project:"プロジェクト一覧",
    general:"一般",
    host_text:"ホスト",
    public_infomation:"公開情報",
    full_name:"フルネーム",
    profile_photo:"プロフィール写真",
    row_1_edit_profile:"正面顔写真をクリアすることは、ホストとゲストがお互いに学ぶ重要な方法です。 あなたの顔をはっきりと示す写真を必ず使用してください。個人または機密情報は含まれておらず、家主やテナントには見えません。",
    upload_ava_text:"デバイスからファイルをアップロードする",
    private_infomation:"個人情報",
    row_2_edit_profile:"私たちはあなたの個人情報を他のProperty Plusユーザーと共有することはありません。",
    i_am:"わたし",
    birth_date:"誕生日",
    email:"Email",
    phone_number:"電話番号",
    verification:"検証",
    row_3_edit_profile:"賃貸借契約を結ぶ際に身分証明書を提示する必要がありますので、今すぐ始めましょう。",
    upload:"アップロード",
    option_infomation:"オプション情報",
    company:"会社",
    company_address:"会社の住所",
    row_4_edit_profile:"緊急の状況で警告できる信頼できる連絡先を顧客サービスチームに提供します。",
    describe_yourself:"あなた自身について説明しなさい",
    your_visiting_list:"あなたの訪問リスト",
    your_apartment:"あなたのアパート",
    visting_schedule:"訪問予定",
    visting_history:"訪問履歴",
    you_visited:"あなたが訪問した",
    apartment:"アパート",
    billing:"請求書",
    send_issue:"問題を送信する",
    your_using_service:"あなたの使用しているサービス",
    service:"サービス",
    quantity:"量",
    maintance_management:"メンテナンスと管理",
    default:"デフォルト",
    cable_tv:"ケーブルテレビ",
    times:"回",
    week:"週間",
    bottles:"ボトル",
    change:"変化する",
    current_balance:"経常収支",
    electricity_charge:"電気料金",
    not_paid:"支払われない",
    paid:"Paid",
    hot_water_charge:"給湯",
    cold_water_charge:"冷水チャージ",
    report_a_problem:"問題を報告します",
    support_inbox:"サポート受信トレイ",
    reported_billing_issue:"請求の問題を報告しました",
    last_update:"最後の更新",
    sending:"送信",
    solved:"解決済み",
    in_progress:"進行中",
    we_sent_you_a_message:"私たちはあなたにメッセージを送った",
    rate_your_experience:"経験を評価する",
    change_your_password:"パスワードを変更してください",
    old_password:"以前のパスワード",
    new_password:"新しいパスワード",
    confirm_new_password:"新しいパスワードを確認",
    passwords_not_match:"パスワードが一致しません",
    update_password:"パスワードの更新",
    pending:"保留中の承認",
    approved:"レビュー済み",
    signupFB:"に登録する Facebook",
    signupGG:"に登録する Google",
    signupEmail:"に登録する Email",
    or:"または",
    signEmail:"登録者 Email",
    haveAccount:"すでにアカウントがあります",
    login:"サインイン",
    loginFB:"にログインする Facebook",
    loginGG:"にログインする Google",
    forgotPW:"パスワードを忘れました",
    dhaveAccount:"まだアカウントがありません",
    signup:"サインアップ",
    signupwith:"登録者",
    bysignin:"サインアップすることで、私は同意します PropertyPlus ",
    termofservice:"任期 ,",
    privacys:"プライバシーポリシー ,",
    and:"と",
    copyright:"著作権",

    career:"キャリア",
    policy:"ポリシー",
    why_host:"なぜ宿主ですか？",
    hosting:"ホスティング",
    community:"コミュニティセンター",
    terms:"条項",
    privacy:"プライバシー",
    site_map:"サイトマップ",

    search_bar_livingHaNoi: "HaNoi での簡単な生活",
    search_bar_price: "価格",
    search_bar_room: "ルーム",
    search_bar_area: "エリア",
    search_bar_facilities: "施設",

    technology:"技術",
    besides:"さらに、PropertyPlusは、顧客全員（テナントと家主）を喜ばせるために、全面的なコントロールのために幅広いピアツーピア情報システムを適用することによって常に努力しています。",
    From:"私たちは、バーチャルリアリティ技術であるMatterportを使用しています.Matterportは、実際に正確な想像力を提供し、直接行くことなくアパートを訪問することができます。 そして、私たちは、あなたが見ていることが本当であることを保証します。",
    canbe:"2020年まで、Property Plusは、電子契約、管理、およびカスタマイズされたサービスの同期システムを構築します。 ハウスキーピングとテクニカルメンテナンスの手順は、自動化されたモバイルアプリケーションを通じて監視されます。 問題発生時の待ち時間を短縮するのに役立ちます。",
    screen:"アパートの検索、契約の締結からアパートの監視まで、世界中のハノイから半分離れた場所にいて、コンピュータの画面上で行うことができます。",

    sv_house:"ハウスキーピング部",
    sv_5star:"5スタースタンダードサービス",
    sv_beinghonest:"最もプロフェッショナルな環境で訓練され、訓練された正直で経験豊かで有能なスタッフであることから、Property PlusのHouse Keeping Deparmentは、最も要求の厳しいお客様を圧倒する自信を持っています。",
    sv_procedure:"手順",
    sv_standard:"標準的な手順は、評判の良い国際的な5つ星ホテルの経験豊富な専門家によって設計され訓練されています",
    sv_trust:"信頼",
    sv_withour:"私たちの正直でフレンドリーなスタッフが、お客様が家にいない時はいつも安心しています。",
    sv_experience:"経験",
    sv_beingable:"関連する問題を最速で最もプロフェッショナルな方法で解決できること。",
    sv_tool:"ツール",
    sv_tools:"ツール、化学物質は、人間、財産、環境に対するサービスの質と安全性を確保するために厳格に管理されています。",
    sv_technique:"テクニック - メンテナンス部門",
    sv_beingalways:"常に顧客のために",
    sv_devoting:"すべての時間を費やすことは、Property Plusメンテナンス技術者の優先事項とスローガンです。当社の従業員は、顧客の生活の中で生じる障害を顧客が解決するのを支援し、支援することが常に可能です",
    sv_speed:"速度",
    sv_presenting:"120分以内にインシデントを検査するための現場でのプレゼンテーション",
    sv_reception:"顧客からの情報の受信",
    sv_responsibility:"責任",
    sv_beingableto:"関連性の高い問題を最も速く最大限に解決できること ",
    sv_professionalway:"プロの方法。",
    sv_management:"経営部",
    sv_resolution:"プロの解像度",
    sv_through:"唯一のホットラインを通じて、顧客のすべての問題はすべての関連部門に伝えられます。",
    sv_communication:"コミュニケーション",
    sv_three:"コミュニケーションの3つの言語：英語、日本語、ベトナム語",
    sv_availability:"可用性",
    sv_availableto:"お客様からのフィードバックを常に受け​​られるようにする",
    sv_attitude:"姿勢",
    sv_working:"心から働き、積極的に耳を傾け、どんな場合でも顧客からのすべての主張とフィードバックを歓迎し、受け入れる",
    
    ab_general:"一般",
    ab_organization:"組織構造",
    ab_company:"会社のモデル",
    ab_history:"形成と発展の歴史",
    ab_vision:"ビジョンと使命",
    ab_core:"コア値",
    ab_development:"開発指向",
    ab_taking:"2011年に設立されたプロパティプラスは、ハノイの高級不動産のコンサルティング、トレーディングおよびリースの分野における3大企業の1つであることを誇りに思っています。当初、アパートの賃貸市場に浸透してきたダイロイは、常にベトナムの不動産価値の高さと、ハノイで働く外国人トレーダーの生活へのより良いサポートに注目しています。ベトナム全般。ダイロイは高級マンション仲介業者の不在を認識して、プロパティプラスを設立し、ベトナムに就職している顧客にプロフェッショナルスタンダードサービスを提供することを最優先課題としています。ベトナムで働く外国人の生活ニーズを満たすために、私たちは常にアパートの価値を高める目的で付加価値サービスを提供するよう努めています。プロパティプラスは、アパートの管理と管理システムにより、個人が所有する高級アパートメントにアクセスする際の顧客の困難を解決しています。さらに、熟練した技術者、熱意、専門的な訓練を受けたスタッフが、高級インフラストラクチャーとユーティリティクラスでの生活を楽しむことができます。私たちの使命は、お客様の生活に快適さ、やすらぎと親しみの要素をもたらすことです。日常生活で起こるすべての問題は私たちによって解決されるでしょう。プロパティプラスは、急速な技術開発と相まって、各国の200人近くの既存顧客を管理する経験を持ち、住宅所有者と住宅所有者の不動産市場を最適化することを目指しています。テナント。住宅所有者は、ハイエンドの物件を希望の価格ですばやく借りることができます。テナントは、標準サービスに関連するすべてのハイエンドプロパティに簡単にアクセスできます。",
    ab_vis:"ビジョン :",
    ab_market:"プロパティプラスは、ベトナムの人々が提供するサービスに関する国際的な顧客の認識を変えたいという希望をもって、外国人のための不動産市場の先頭に立つことを目指しています。ベトナムでは世界クラスのサービスを提供しています。",
    ab_mission:"ミッション :",
    ab_concerned:"私たちは、個々の住宅所有者と外国人が日常の住宅問題や問題を心配することなく、快適に生活を楽しむことができる家を借りるのを手伝っています。",
    ab_cor:"コア値",
    ab_isalways:"プロパティプラスの基盤は、投資家、パートナー、顧客、従業員および社会全体との関係に基づいています. プロパティプラスは、それがあらゆるビジネスにとって最も貴重なものであることを理解しています。 PROPERTY PLUSは価値を維持し、それらの関係を強化することに専念しています。",
    ab_creativity:"1.創造：常に革新し、改善し、発展させる。敢えて考えようとする勇気の精神を高めてください。",
    ab_commit:"2.信頼性：適切かつ高いレベルのコミットメントを確保するための努力を最大限に活用します。",
    ab_orientation:"3.方向性：開拓の願望は新しい傾向を作り出します。",
    ab_conscientious:"4.焦点：心からのボランティアと興奮でお客様の世話をしてください。",
    ab_cooperation:"5.協力：顧客、パートナー、同僚、投資家、そして社会全体との関係を尊重する。",   
    ab_minh:"長所と開発の方向性を備えたPROPERTY PLUSは、今後5年間で家主と長期テナントを結ぶベトナム最大のプラットフォームになることを目指しています。この数字はベトナムのハイエンドマンション総数の5％を占める15,000件で、ハノイ、ホーチミン、ダナン、ハイフォン、ニャチャンなどの主要都市で利用可能です。",
    abu_business:"事業の型",
    abu_tenants:"テナントの利益",
    abu_landlord:"家主の利益",
    abu_friendly:"Property Plusは、コミュニティの各受益者にとって複雑でユーザーフレンドリーな統合モデルを構築するためのものです。",
    abu_butle:"専用バートル",
    abu_large:"魅力的な価格の大型で美しいアパートメント。",
    abu_reception:"•プロの受付と管理",
    abu_good:"•ジム、スイミングプールなどの優れたロケーションと最高の施設",
    abu_star:"•5つ星の標準的なハウスキーピングサービス",
    abu_periodic:"•Property Plusの入力管理標準に基づく定期的な技術的メンテナンス",
    abu_procedural:"• •手続きサポート：オンラインリース契約、納税、請求書支払いなど",
    abu_security:"• 高いセキュリティ：マンション、火災安全、社会問題の安全にアクセスするQRコード。",
    abu_discover:"•地元の文化や人生に発見し、統合する機会。",
    abu_house:"プロフェッショナルハウスマネージャー",
    abu_pp:"PPはベトナムで経験豊かで経験豊富な不動産ブローカーのチームを擁し、可能な限り短時間であなたのアパートが潜在的なテナントに手を差し伸べるのを助けます。次にProperty Plusは、契約、管理、財務、および保守のすべてのリースを管理します。",
    abu_dedicated:"•24時間年中無休のカスタマーサポートを提供する専門知識のあるコンサルタント。",
    abu_marketing:"•マルチチャネルのテナントのマーケティングと検索。",
    abu_optimizing:"•アパートの空き時間を短期レンタルサービスで最適化する。",
    abu_procedural:"•手続きサポート：オンラインリース契約、納税、請求書支払いなど",
    abu_standard:"•5つ星の標準的なハウスキーピングサービス",
    abu_periodic:"•Property Plusの入力管理基準に基づく定期的な技術的メンテナンス。",
    abu_free:"•テクニカルメンテナンスのための300万VND /年の無料手当。",
    abu_security:"•高度なセキュリティ：QRコードとアパートメント監視ソフトウェアを使用します。",
    abu_parties:"•当事者間のすべての手続きにおける情報の透明性。",
    ab_team:"私たちのチーム",
    ab_ceo:"CEO＆創業者",
    ab_staff:"優れたスタッフ",

    our_technology:"当社の技術",
    apartment_searching_platform:"アパート検索プラットフォーム",
    mutil_party_communication_system:"多者通話システム",
    service_and_management_system:"サービスと管理システム",
    customer_realationship_management_system:"顧客関係管理システム",
    explore_our_tech:"私たちの技術を探る",  

    content_about_us:"<p>心の深みから、新しい国に定着することはすばらしく思い出深いものでなければならず。プロパティプラスは国際的な友人に快適な生活空間を提供するよう努めています。 、豪華さ、快適さと歓迎の感覚はお客様が踏み込んだ瞬間からです。</p>"+
                    "<p>プロパティプラスでは次のことが可能です。</p>"+
                    "<p>手頃な価格で豪華なインフラストラクチャーと世界一のアメニティでの生活をお楽しみください。</p>"+
                    "<p>経験豊富で熱心な技術者で、専門的に5つ星の訓練を受けています。</p>"+
                    "<p>お客様に最適なスペースとサービスを持つ人を体験してください。</p>"+
                    "<p>スタッフによるサービス - 技術者は経験豊かで熱心で、専門的に5つ星の訓練を受けています。</p>"+
                    "<p>仕事と楽しみの間の人生のバランスをとる。</p>"+
                    "<p>プロパティプラスでは、どこに家がありますか。</p>",
    po_policy:"個人情報保護方針",
    po_propertyplus:"Propertyplus.com.vnは、Dai Loi Trade and Consultancy of Real Estate Co. Ltd（「Property Plus」、「Us」、「We」、または「Our」）が所有し、運営しています。 このプライバシーポリシーは、www.propertyplusに掲載されているウェブサイトから提供されているProperty Plusのサービスに関連してお客様が提供する個人識別可能な情報（「個人データ」）の収集、使用、開示、処理および保護について説明しています。 com.vn. 個人情報とは、個人の個人情報を意味します。本サイトへの参照は、モバイルウェブサイトやアプリケーションを含むがこれに限定されない、その派生物を含むものとみなされます。 本サイトを訪問または使用することにより、本プライバシーポリシーおよび/またはウェブサイト規約に従って、お客様の個人データの収集、使用、開示および処理に同意し、同意するものとします。 以下のプライバシーポリシーに同意しない場合は、すぐにサイトを離れてください。",
    po_fromtime:"Property Plusは、法律、個人データの収集および使用の実践、当社サイトの機能、または技術の進歩の変化を反映するために、このプライバシーポリシーを随時変更する可能性があります。 当社がお客様の個人データを収集または使用する方法を変更する改正を行った場合、その変更は本プライバシーポリシーに掲載され、適用日はこのプライバシーポリシーの冒頭に記載されます。 したがって、このプライバシーポリシーを定期的に見直し、最新の方針と実践について最新のものにする必要があります。 Property Plusは、変更を実施する前に、重要な変更を顕著に掲載する予定です。 プライバシーポリシーの変更または変更に同意しない場合は、サイトの使用を継続しないでください。 あなたは、変更の有効日後にサイトを使用する際に、プライバシーポリシーの変更に同意したものとみなされます。",
    po_collect:"1.収集する情報",
    po_we:"当社は、本サイトを使用する際にお客様が提供する個人データを収集します。 これには、お客様の氏名、Property PlusユーザーIDとログイン資格情報、住所、電話番号、Eメールアドレス、ホテル名、ホテルの所在地、滞在日数などが含まれますが、これに限定されません。 また、インターネットプロトコル（IP）アドレス、地理的位置、オペレーティングシステムの種類、国籍、検索設定、その他の一般的なインターネット利用に関するその他の個人情報も収集します。",
    po_howwe:"2.あなたの情報をどのように使用するか",
    po_wemay:"当社は、お客様の個人データおよび本サイトを通じて収集されたその他の情報を、以下の目的のために使用することがあります。",
    po_registering:"•サイトの使用および/またはアクセスの登録、管理および/または管理。",
    po_managing:"•サイト上で提供されるサービスの管理、操作、管理、提供。",
    po_contacting:"•サイト上のサイトおよびサービスの利用および/またはアクセス、およびサイトまたはその他の方法によりお客様から提出された照会および/または要求に関連する事項についてお客様に連絡する。",
    po_customize:"•サイトの使用経験をカスタマイズする。",
    po_measuring:"•顧客の経験と満足度を測定し改善する。",
    po_publishing:"•サイト、旅行代理店、航空券、ホテルなどの顧客のレビューを、デジタルおよび/または印刷形式で公開アクセス用に公開する。",
    po_enforce:"•利用規約を強制する。",
    po_resolve:"紛争や苦情を解決し、支払いや手数料を徴収し、問題を解決する。 および/または",
    po_purposes:"•それ以外の目的では、収集時点で利用可能になります。",
    po_wemayalso:"また、ソーシャルメディアマーケティングのために収集された個人情報およびその他の情報を、直接的およびオープンなグラフ手法を使用して使用することもできます。 新製品についてダイレクトメーラーに送信するなどのデジタルおよび従来のマーケティング目的や、興味深いと思われる特別提供またはその他の情報については、 弊社がいつでもあなたに送ることができるマーケティング資料をオプトアウトすることができます。 マーケティング資料からオプトアウトすることを選択した場合は、当社のマーケティング資料に記載されている購読解除の手順に従ってください。",
    po_sharing:"3.個人データの共有と転送",
    po_your:"お客様の個人情報は、Property Plusによって当社の関連会社に共有される場合があります。 Property Plus（および/またはその関連会社）は、上記の目的の1つまたは複数の目的で、第三者のサービスプロバイダ、サプライヤまたは代理店にお客様の個人情報を開示することがあります。 サードパーティのサービスには、ウェブサイトのホスティング、データ分析、マーケティング、クレジットカード処理の処理、サービス提供などが含まれますが、これらに限定されません。",
    po_please:"Property Plusは、以下の状況でお客様の個人情報を開示する場合があります。",
    po_bring:"•請求または訴訟を提起または擁護すること。",
    po_comply:"•法執行当局または当局による裁判所命令、司法手続き、正当な要請、ワラントまたはこれに相当するものを遵守すること。",
    po_investigate:"•適用法を遵守するため、または当社の正当な利益を保護するために、詐欺またはその他の不正行為を調査するため、または必要または必要に応じて調査すること。",
    po_purchasers:"•当社の事業または会社の全部または一部の売却、譲渡、その他の移転に関連して購入者に。",
    po_apply:"•当社製品およびサービスに適用される条件を適用または適用する。",
    po_therights:"•Property Plusの裁量により、Property Plus、他のサイトユーザ、または他の人の権利、財産または安全を保護する。",
    po_situations:"•法律上認められているその他の状況。",
    po_consent:"4.同意",
    po_as:"上記のように、サイトの閲覧、使用、サイトからの商品の注文、サイトへのサービスの登録または使用、またはサイトで新しいアカウントを作成する際に「確認」ボタンまたは同等のボタンをクリックすることにより、",
    po_consentto:"•上記の目的のために上記の個人情報を収集、使用、開示および/または処理するProperty Plusおよび/またはProperty Plusの関連会社に同意する。",
    po_withdrawing:"5.同意を取り消す",
    po_youmay:"お客様は、合理的な通知をすることにより、いつでもお客様の個人情報の収集、使用または開示に対する同意を取り消すことができます。 同意を取り消したい場合は、下記の連絡先までご連絡ください。 法律で要求されている場合を除き、あるいは当社が正当なビジネス上または法律上の目的を保持している場合を除き、通知時にお客様の個人情報の収集、使用または開示を中止します。 お客様の個人情報の収集、使用または開示に対する同意を撤回することにより、当社は当社のサービスを継続して提供することができない可能性があり、お客様は当社のサービスから生じる損失または損害について、 そのようなサービスの終了に関連して。",
    po_cookie:"6.クッキーポリシー",
    po_acookie:"「クッキー」とは、お客様が当社のサイトにアクセスした際に、お客様のウェブブラウザを通じてハードドライブまたはメモリーカードに転送する英数字の識別子です。 これにより、お客様が当社のサイトを再度訪問し、お客様へのサービスを向上させる際に、当社のシステムがお客様を認識することが可能になります。 この情報は、サイトの訪問者の使用状況を追跡し、サイトの活動に関する統計レポートをコンパイルするために使用されます。 クッキーの詳細については、www.aboutcookies.orgをご覧ください。",
    po_cookies:"また、Cookieは、最も頻繁に訪問される当サイトの領域に関する集約情報を作成するためにも使用されます。 この交通情報は、当社サイトのコンテンツを向上させ、お客様のサイトをより簡単に使用するために使用することができます。 Cookieを拒否するには、ブラウザでCookieを拒否します。 ただし、ブラウザからCookieを削除すると、一部のGoogleサイト機能が機能しなくなることがあります。 クッキーを有効にしない場合は、サイトを限定的にしか使用できない場合があります。",
    po_access:"7.個人データへのアクセスまたは修正",
    po_whenyou:"あなたが私たちにあなたの個人情報を提供するとき、それが正確で完全であることを確認してください。 当社が所有する情報に間違いや間違いが含まれていると思われる場合は、サイト上のお客様のアカウントにログインし、情報を修正してください。 さらに、変更があった場合、適時にお客様のアカウントを通じて個人情報を更新してください。",
    po_ifyou:"あなたが所有する個人データの中で、当社のサイトを通じて修正することができない、または当社が所有または管理している個人データにアクセスすることができない、または適用される法律の規定に従って、エラーまたは省略を修正したい場合は、 下記の連絡先をご利用ください。 当社は、アクセス要求に応答する追加費用を回収する目的で、個人データへのアクセスに合理的な料金を請求することがあります。",
    po_toprotect:"お客様のプライバシーとセキュリティを保護するために、私たちはアクセスを許可する前に、またはあなたの個人データを変更する前にあなたの身元を確認します。 私たちは、例外が適用されない限り、できるだけ早くあなたの個人データへのアクセスまたは修正の要求に答えるよう努めます。",
    po_personal:"8.個人データの保護",
    po_arrangements:"当社は、不正アクセス、収集、使用、開示、複製、改変、処分または同様のリスクを防止するために、物理的、技術的および組織的手続きを含む合理的なセキュリティ対策を維持することにより、個人データを保護します。",
    po_links:"9.他のウェブサイトへのリンク",
    po_oursite:"当社のサイトには他の関心のあるウェブサイトへのリンクが含まれている場合があり ただし、これらのリンクを使用してサイトを離れると、他のウェブサイトを管理することはできません。 当社は、他のウェブサイトのプライバシーに関する慣行については責任を負いませんので、お客様が訪問する各ウェブサイトの個人情報を収集するプライバシーに関する声明を読むようお勧めします。",
    po_registration:"10.登録とメンバーシップ",
    po_allows:"このサイトでは、提供したデータに基づいて、メンバーシップレジスタを持つユーザーアカウントを作成することができます。 データを提供し、登録し、アカウントを作成することによって、あなたは以下を保証します：",
    po_least:"1.あなたは少なくとも18歳です。",
    po_true:"2.あなたに関する情報は、本サイトの登録フォーム（「登録データ」）で必要に応じて、正確かつ正確かつ最新かつ完全です。 そして",
    po_update:"3.この登録データを更新して、それが真実で正確かつ完全であるようにします。",
    po_further:"さらに、あなたは、Property Plusが、お客様、お客様または第三者が、お客様から与えられた不正確または不完全な情報によって生じた損害または損害が発生した場合の損失または損害について一切の責任を負わないことに同意するものとします。登録後、パスワードとユーザーID（「ユーザー名」）を受け取ります。あなたは、パスワードとユーザー名の機密性を維持する責任を負い、ユーザー名またはパスワードに関連するすべての活動について完全に責任を負うものとします。一度に1つのユーザー名とパスワードしか使用できず、複数のユーザー名を使用することはできません。あなたのパスワードはあなたの個人的な使用のためだけであり、あなたはパスワードを厳重に秘密にすることに同意するものとします。お客様は、パスワードやアカウントの不正使用、またはその他のセキュリティ違反について、Property Plusに直ちに通知することに同意するものとします。セキュリティを強化するため、本サイトを使用するたびにアカウントからログアウトまたは終了するようにしてください。お客様は、本条項の遵守を怠った場合に発生した当社、お客様または第三者が被った損失または損害について、Property Plusは責任を負いません。",
    po_transfer:"11.事業譲渡",
    po_event:"サイトを含むProperty Plus事業または会社の全部または一部の支配権の変更または所有権の変更が生じた場合、すべてのユーザーの個人データは、そのような資産の譲渡の一部となります。",
    po_approval:"12.プライバシーポリシーの変更の承認",
    po_provide:"本サイトまたは当社が提供するサービスを使用することにより、このプライバシーポリシーに記載されている個人データの収集、使用、開示および処理に同意するものとします。 さらに、当社のサービスを利用する場合、当社は本プライバシーポリシーに従ってお客様の個人情報を収集、使用、開示、処理する権利を有します。 Property Plusは、このプライバシーポリシーを随時変更することがあります。 私たちは変更を行う前に、このサイトの変更を表示します。",
    po_precedence:"13.優先順位",
    po_inconsistency:"当社のウェブサイト規約に同意した場合、当該ウェブサイト規約と本プライバシーポリシーとの間に矛盾が生じた場合は、ウェブサイト規約が優先されます。",
    po_contactus:"14.お問い合わせ",
    po_questions:"このプライバシーポリシーに関するご質問やご要望がございましたら、データ保護担当者に以下の詳細、またはプロパティプラスのような担当者に、手紙、請求書、Eメールまたはサイト：support @ propertyplusを通知することによって指定することができます。 com.vn",
    po_date:"発効日：01/01/2019",

}

app.config(['$translateProvider', function ($translateProvider) {
    // add translation tables
    $translateProvider.translations('en', translationsEN);
    $translateProvider.translations('vi', translationsVI);
    $translateProvider.translations('jp', translationsJP);
    $translateProvider.preferredLanguage('en');
    $translateProvider.fallbackLanguage('vi');
    $translateProvider.fallbackLanguage('jp');
}]);